export const manuscriptSampleBooks = [
  {
    slug: "awesome-boys",
    // Watermark policy for current and future books: always monochrome.
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Awesome_Boys_Coloring_Book_interior.pdf",
    coverPdf: "scripts/temp-manuscripts/Awesome_Boys_Coloring_Book_cover (1).pdf",
    outputDir: "public/images/books/manuscript-samples/awesome-boys",
    lookInside: {
      outputDir: "public/images/books/previews/awesome-boys",
      pageRange: {
        start: 9,
        end: 88,
      },
      // Optional override exists, but mono is the only allowed value.
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "awesome-girls",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Awesome_Girls_manuscript.pdf",
    coverPdf: "scripts/temp-manuscripts/Awesome_Girls_cover (2).pdf",
    outputDir: "public/images/books/manuscript-samples/awesome-girls",
    lookInside: {
      outputDir: "public/images/books/previews/awesome-girls",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "pizza-sweet-treats",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Pizza__Sweet_Treats_manuscript (1).pdf",
    coverPdf: "scripts/temp-manuscripts/Pizza__Sweet_Treats_cover (1).pdf",
    outputDir: "public/images/books/manuscript-samples/pizza-sweet-treats",
    lookInside: {
      outputDir: "public/images/books/previews/pizza-sweet-treats",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "blast-off-space",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Blast_Off_A_Fun_Space_Coloring__manuscript.pdf",
    coverPdf: "scripts/temp-manuscripts/Blast_Off_A_Fun_Space_Coloring__cover.pdf",
    outputDir: "public/images/books/manuscript-samples/blast-off-space",
    lookInside: {
      outputDir: "public/images/books/previews/blast-off-space",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "mighty-machines",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Mighty_Machines_manuscript.pdf",
    coverPdf: "scripts/temp-manuscripts/Mighty_Machines_cover.pdf",
    outputDir: "public/images/books/manuscript-samples/mighty-machines",
    lookInside: {
      outputDir: "public/images/books/previews/mighty-machines",
      pageRange: {
        start: 9,
        end: 98,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 99,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "enchanted-easter",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Enchanted_Easter_manuscript (1).pdf",
    coverPdf: "scripts/temp-manuscripts/Enchanted_Easter_cover (4).pdf",
    outputDir: "public/images/books/manuscript-samples/enchanted-easter",
    lookInside: {
      outputDir: "public/images/books/previews/enchanted-easter",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "coloring-emotions",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Coloring_Emotions_manuscript (2).pdf",
    coverPdf: "scripts/temp-manuscripts/Coloring_Emotions_cover (2).pdf",
    outputDir: "public/images/books/manuscript-samples/coloring-emotions",
    lookInside: {
      outputDir: "public/images/books/previews/coloring-emotions",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "magical-creatures",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Magical_Creatures_manuscript (1).pdf",
    coverPdf: "scripts/temp-manuscripts/Magical_Creatures_cover (4).pdf",
    outputDir: "public/images/books/manuscript-samples/magical-creatures",
    lookInside: {
      outputDir: "public/images/books/previews/magical-creatures",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "chic-styles",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Chic_Styles_manuscript (1).pdf",
    coverPdf: "scripts/temp-manuscripts/Chic_Styles_cover (6).pdf",
    outputDir: "public/images/books/manuscript-samples/chic-styles",
    lookInside: {
      outputDir: "public/images/books/previews/chic-styles",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "dresses-and-dolls",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Dresses__Dolls__manuscript.pdf",
    coverPdf: "scripts/temp-manuscripts/Dresses__Dolls__cover (5).pdf",
    outputDir: "public/images/books/manuscript-samples/dresses-and-dolls",
    lookInside: {
      outputDir: "public/images/books/previews/dresses-and-dolls",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "style-time-machine",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Style_Time_Machine_manuscript.pdf",
    coverPdf: "scripts/temp-manuscripts/Style_Time_Machine_cover (2).pdf",
    outputDir: "public/images/books/manuscript-samples/style-time-machine",
    lookInside: {
      outputDir: "public/images/books/previews/style-time-machine",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "easy-animals",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Easy_Animals_Coloring_Book_manuscript (6).pdf",
    coverPdf: "scripts/temp-manuscripts/Easy_Animals_Coloring_Book_cover (11).pdf",
    outputDir: "public/images/books/manuscript-samples/easy-animals",
    lookInside: {
      outputDir: "public/images/books/previews/easy-animals",
      pageRange: {
        start: 9,
        end: 108,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 109,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "awesome-airplanes",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Awesome_Airplanes__manuscript.pdf",
    coverPdf: "scripts/temp-manuscripts/Awesome_Airplanes__cover (1).pdf",
    outputDir: "public/images/books/manuscript-samples/awesome-airplanes",
    lookInside: {
      outputDir: "public/images/books/previews/awesome-airplanes",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
  {
    slug: "alphabet-coloring-book",
    watermarkTheme: "mono",
    sourcePdf: "scripts/temp-manuscripts/Alphabet_Coloring_Book_manuscript.pdf",
    coverPdf: "scripts/temp-manuscripts/Alphabet_Coloring_Book_cover (2).pdf",
    outputDir: "public/images/books/manuscript-samples/alphabet-coloring-book",
    lookInside: {
      outputDir: "public/images/books/previews/alphabet-coloring-book",
      pageRange: {
        start: 9,
        end: 88,
      },
      watermarkTheme: "mono",
    },
    outputSize: 1400,
    renderZoom: 2.35,
    assets: [
      {
        type: "pdf-panel",
        panel: "front",
        page: 1,
        watermark: "none",
        output: "00-front-cover.webp",
      },
      {
        type: "pdf-page",
        page: 1,
        watermark: "none",
        output: "01-front-title.webp",
      },
      {
        type: "pdf-page",
        page: 3,
        watermark: "none",
        output: "03-front-copyright.webp",
      },
      {
        type: "pdf-page",
        page: 5,
        watermark: "none",
        output: "05-front-belongs.webp",
      },
      {
        type: "pdf-page",
        page: 7,
        watermark: "none",
        output: "07-front-color-test.webp",
      },
      {
        type: "pdf-page",
        page: 9,
        watermark: "none",
        output: "09-interior-001.webp",
      },
      {
        type: "pdf-page",
        page: 89,
        watermark: "none",
        output: "10-back-about-author.webp",
      },
      {
        type: "pdf-panel",
        panel: "back",
        page: 1,
        watermark: "none",
        output: "12-back-cover.webp",
      },
    ],
  },
];