/**
 * validate-post.mjs — deterministic QA gate for AI-generated social posts.
 *
 * Implements the 20 blocking rules (V1-V20) and 4 warnings (W1-W4) defined in
 * GROWTH_CONTENT_PLAYBOOK.md §11. Pure, side-effect free, no network calls.
 *
 * USAGE (as a library):
 *   import { validatePost, injectUtms } from "./validate-post.mjs";
 *   const result = validatePost(post, { type, lang, history });
 *   if (!result.ok) { ... retry or skip ... }
 *
 * USAGE (as a CLI, for ad-hoc testing):
 *   node scripts/social/validate-post.mjs --file path/to/post.json --type free-coloring --lang en
 *   node scripts/social/validate-post.mjs --stdin --type free-coloring --lang en  < post.json
 *
 * The post object shape (matches generateAIPost output in ai-generate.mjs):
 * {
 *   concept: string,
 *   creativeId?: string,
 *   flywheelStage?: number,
 *   platforms: {
 *     bluesky:   { text, hashtags },
 *     facebook:  { text, hashtags },
 *     instagram: { text, hashtags },
 *   }
 * }
 *
 * Context shape:
 * {
 *   type: "book-promo" | "free-coloring" | ... ,
 *   lang: "en" | "es",
 *   history?: Array<{ type: string, postedAt: string, platforms: {...} }>,
 *   realGalleryReviewCount?: number,  // for V19
 * }
 */

import { readFileSync } from "node:fs";
import { buildUtmUrl } from "./content-templates.mjs";

const SITE_URL = "https://www.littlechubbypress.com";

// ─── Banned / watch phrases ────────────────────────────────────────────────

const URGENCY_PHRASES = [
  // English
  "buy now", "order now", "limited time", "don't miss", "dont miss",
  "hurry", "click the link", "last chance", "only today", "act fast",
  "going fast", "while supplies last",
  // Spanish
  "compra ya", "compra ahora", "pide ya", "pide ahora",
  "no te lo pierdas", "ultima oportunidad", "última oportunidad",
  "solo hoy", "date prisa", "apúrate", "apurate",
  "haz clic en el enlace", "haga clic en el enlace",
];

const NONEXISTENT_FEATURE_PHRASES = [
  // V5 — suggests features our site does not have
  "upload your kid's art", "upload your kids art", "upload your child's art",
  "upload your drawing", "upload your coloring", "share your photo",
  "post your kid's drawing", "post your child's artwork",
  "sube el arte de tu", "sube tu dibujo", "sube tu foto",
  "publica el dibujo de tu", "envia el dibujo",
];

const PRIVACY_FORBIDDEN = [
  // V15 — things we must never say
  "ai-generated illustration", "ai generated illustration",
  "ai-generated images", "generated by ai", "made by ai",
  "ilustracion generada por ia", "ilustración generada por ia",
  "generado por ia", "hecho con ia",
];

// Short, well-known acronyms allowed in ALL CAPS (V16 whitelist)
const ALLCAPS_WHITELIST = new Set([
  "AMAZON", "KDP", "USA", "UK", "EU", "PDF", "URL", "CTA",
  "FAQ", "DIY", "PRO", "NEW", "FREE", // FREE is borderline but common
  "BOGO", "IG", "FB", "IT", "OK", "VIP", "OMG", "LOL",
  // Brand currency labels used as list headers (e.g. "🎟️ TICKETS: do X")
  "TICKETS", "PEANUTS", "TICKET", "PEANUT",
]);

// Platform-specific hashtag count ranges (V17)
const HASHTAG_RANGE = {
  bluesky: [2, 3],
  facebook: [3, 5],
  instagram: [8, 15],
};

// Character budget for Bluesky (V8)
const BLUESKY_MAX_CHARS = 300; // ATProto actual cap; §11 says 280, we use 300 to match ai-generate.mjs enforcement

// ─── Utilities ──────────────────────────────────────────────────────────────

/** Count emoji-presentation codepoints in a string. */
function countEmojis(text) {
  if (!text) return 0;
  // Matches most emoji (incl. symbols with VS16) + ZWJ sequences (counted as 1 grapheme)
  const re = /\p{Extended_Pictographic}/gu;
  const matches = text.match(re) || [];
  return matches.length;
}

/** Extract all http(s) URLs from text. */
function extractUrls(text) {
  if (!text) return [];
  const re = /https?:\/\/\S+/gi;
  return text.match(re) || [];
}

/** True if the URL is on our own domain. */
function isSiteUrl(url) {
  return url.startsWith(SITE_URL) || url.includes("littlechubbypress.com");
}

/** True if the URL points to Amazon (any locale / any shortener). */
function isAmazonUrl(url) {
  return /\b(amazon\.[a-z.]+|amzn\.to|a\.co)\b/i.test(url);
}

/** Count hashtags in a string (supports `#` tokens separated by space or line). */
function countHashtags(str) {
  if (!str) return 0;
  const re = /#[\w\u00C0-\u024F]+/g;
  return (str.match(re) || []).length;
}

/** Get combined text+hashtags (what the reader actually sees). */
function fullText(variant) {
  if (!variant) return "";
  const t = variant.text || "";
  const h = variant.hashtags || "";
  return h ? `${t}\n\n${h}` : t;
}

/** Normalize for phrase matching (lowercase, strip accents-optional). */
function norm(s) {
  return (s || "").toLowerCase();
}

/** Simple token-overlap ratio (Jaccard) on the first N words. Used for V14. */
function openingSimilarity(a, b, firstWords = 8) {
  const tok = (s) =>
    norm(s)
      .replace(/[^\p{L}\p{N}\s]/gu, " ")
      .split(/\s+/)
      .filter(Boolean)
      .slice(0, firstWords);
  const A = new Set(tok(a));
  const B = new Set(tok(b));
  if (A.size === 0 || B.size === 0) return 0;
  let inter = 0;
  for (const w of A) if (B.has(w)) inter += 1;
  return inter / (A.size + B.size - inter);
}

// ─── Public: UTM injection helper ──────────────────────────────────────────

/**
 * Rewrite any raw site URL inside the post text to include standard UTMs.
 * Idempotent — URLs that already carry `utm_source` are left alone.
 * Amazon / external URLs are untouched.
 *
 * @param {object} post — mutated in place AND returned
 * @param {object} ctx  — { type, lang }
 */
export function injectUtms(post, ctx = {}) {
  if (!post?.platforms) return post;
  const { type = "organic", lang = "en" } = ctx;
  const today = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const campaign = `sprint-${type}`;

  for (const platform of Object.keys(post.platforms)) {
    const variant = post.platforms[platform];
    if (!variant?.text) continue;
    variant.text = variant.text.replace(/https?:\/\/\S+/gi, (url) => {
      if (!isSiteUrl(url)) return url; // leave Amazon / external alone
      if (/utm_source=/i.test(url)) return url; // already tagged
      const content = `${type}-${today}-${platform[0]}-${lang}`;
      return buildUtmUrl(url, { source: platform, campaign, content });
    });
  }
  return post;
}

// ─── Individual rule checks ─────────────────────────────────────────────────
// Each returns an array of violations (usually 0 or 1).

function checkV1_emojiCount(platform, variant) {
  const count = countEmojis(fullText(variant));
  // Bluesky is emoji-shy; other platforms tolerate up to 3 (needed for 🎟️/🥜 currency labels).
  const limit = platform === "bluesky" ? 2 : 3;
  if (count > limit) {
    return [{
      id: "V1", platform, severity: "block",
      message: `Emoji count ${count} > ${limit} (found in ${platform}).`,
    }];
  }
  return [];
}

function checkV2_urgency(platform, variant) {
  const hay = norm(fullText(variant));
  const hit = URGENCY_PHRASES.find((p) => hay.includes(p));
  if (hit) {
    return [{
      id: "V2", platform, severity: "block",
      message: `Urgency/ad-speak phrase "${hit}" is banned.`,
    }];
  }
  return [];
}

function checkV3_peanutsFromReviews(platform, variant) {
  const hay = norm(fullText(variant));
  // Only flag CAUSAL statements ("peanuts from review", "review earns peanut").
  // Avoid false positives on contrast phrasing ("tickets from reviews, peanuts from sharing").
  const patterns = [
    /peanuts?\s+(from|for|per|by|when|after|upon)\s+(a\s+|writing\s+|submitting\s+|leaving\s+|posting\s+)?reviews?/i,
    /reviews?\s+(earn|give|get|award|unlock)s?\s+[^.,;\n]{0,20}peanuts?/i,
    /earn\s+peanuts?\s+[^.,;\n]{0,15}(writing|submitting|leaving|posting)\s+[^.,;\n]{0,10}reviews?/i,
    // Spanish
    /peanuts?\s+(por|al|cuando)\s+(dejar|escribir|publicar|enviar)?\s*(una\s+|la\s+)?reseñ/i,
    /reseñ[a-z]*\s+(gana|da|otorga|entrega)s?\s+[^.,;\n]{0,20}peanuts?/i,
  ];
  if (patterns.some((r) => r.test(hay))) {
    return [{
      id: "V3", platform, severity: "block",
      message: "Post says Peanuts are earned from reviews. Peanuts come from SHARES; reviews earn Tickets.",
    }];
  }
  return [];
}

function checkV4_ticketsFromShares(platform, variant) {
  const hay = norm(fullText(variant));
  const patterns = [
    /tickets?\s+(from|for|per|by|when|after|upon)\s+(a\s+|sharing\s+|posting\s+|sending\s+)?shar/i,
    /shar[a-z]*\s+(earn|give|get|award|unlock)s?\s+[^.,;\n]{0,20}tickets?/i,
    /earn\s+tickets?\s+[^.,;\n]{0,15}shar/i,
    /tickets?\s+(por|al|cuando)\s+(compartir|enviar|publicar)/i,
    /compart[a-z]*\s+(gana|da|otorga|entrega)s?\s+[^.,;\n]{0,20}tickets?/i,
  ];
  if (patterns.some((r) => r.test(hay))) {
    return [{
      id: "V4", platform, severity: "block",
      message: "Post says Tickets are earned from sharing. Tickets come from REVIEWS; shares earn Peanuts.",
    }];
  }
  return [];
}

function checkV5_nonexistentFeature(platform, variant) {
  const hay = norm(fullText(variant));
  const hit = NONEXISTENT_FEATURE_PHRASES.find((p) => hay.includes(p));
  if (hit) {
    return [{
      id: "V5", platform, severity: "block",
      message: `Suggests nonexistent feature ("${hit}"). The site only accepts structured book reviews, not art uploads.`,
    }];
  }
  return [];
}

function checkV6_shareAsImage(platform, variant) {
  const hay = norm(fullText(variant));
  // Describes sharing as posting/sending an image rather than sharing a link
  const patterns = [
    /share a (photo|picture|image|pic) (of )?your/i,
    /post a (photo|picture|pic) of your (kid|child|drawing)/i,
    /send us a (photo|picture) of your (kid|child|drawing)/i,
    /comparte una (foto|imagen) de tu (hijo|nino|niño|dibujo)/i,
  ];
  if (patterns.some((r) => r.test(hay))) {
    return [{
      id: "V6", platform, severity: "block",
      message: "Describes sharing as posting an image. Sharing means sending a LINK to a gallery review or coloring page.",
    }];
  }
  return [];
}

function checkV7_instagramUrl(variant) {
  const text = variant?.text || "";
  if (/https?:\/\//i.test(text)) {
    return [{
      id: "V7", platform: "instagram", severity: "block",
      message: "Instagram text contains a URL. Instagram URLs are not clickable — use 'Link in bio'.",
    }];
  }
  return [];
}

function checkV8_blueskyLength(variant) {
  // Measure the FULL posted text (text + hashtags appended at send time),
  // not just variant.text — post.mjs auto-truncates at 297 but that silently
  // drops the hashtags. Better to block and retry with a shorter draft.
  const full = fullText(variant);
  if (full.length > BLUESKY_MAX_CHARS) {
    return [{
      id: "V8", platform: "bluesky", severity: "block",
      message: `Bluesky full text (text + hashtags) is ${full.length} chars, over the ${BLUESKY_MAX_CHARS} limit.`,
    }];
  }
  return [];
}

function checkV9_amazonInNonBookPromo(platform, variant, type) {
  if (type === "book-promo") return [];
  const urls = extractUrls(fullText(variant));
  const amz = urls.find(isAmazonUrl);
  if (amz) {
    return [{
      id: "V9", platform, severity: "block",
      message: `Post type is "${type}" (not book-promo) but contains an Amazon URL: ${amz}`,
    }];
  }
  return [];
}

function checkV10_amazonAsPrimaryCta(platform, variant, type) {
  if (type === "book-promo") return [];
  const text = fullText(variant);
  // Heuristic: Amazon URL in the last 120 chars = primary CTA position
  const tail = text.slice(-120);
  if (extractUrls(tail).some(isAmazonUrl)) {
    return [{
      id: "V10", platform, severity: "block",
      message: `Amazon link appears in CTA position on a non-book-promo post.`,
    }];
  }
  return [];
}

function checkV11_utmsMissing(platform, variant) {
  const violations = [];
  for (const url of extractUrls(fullText(variant))) {
    if (!isSiteUrl(url)) continue; // Amazon/external exempt
    const hasAll =
      /[?&]utm_source=/i.test(url) &&
      /[?&]utm_medium=/i.test(url) &&
      /[?&]utm_campaign=/i.test(url);
    if (!hasAll) {
      violations.push({
        id: "V11", platform, severity: "block",
        message: `Site URL missing utm_source/utm_medium/utm_campaign: ${url}. Run injectUtms() before validation.`,
      });
    }
  }
  return violations;
}

function checkV12_brandHashtag(platform, variant) {
  const h = norm(variant?.hashtags || "") + " " + norm(variant?.text || "");
  if (!h.includes("#littlechubbypress")) {
    return [{
      id: "V12", platform, severity: "block",
      message: "#LittleChubbyPress is missing from hashtags.",
    }];
  }
  return [];
}

function checkV13_bookPromoFrequency(type, history) {
  if (type !== "book-promo") return [];
  if (!Array.isArray(history) || history.length === 0) {
    return [{
      id: "V13", platform: "*", severity: "skipped",
      message: "History not provided — V13 frequency check skipped.",
    }];
  }
  const sevenDaysMs = 7 * 24 * 60 * 60 * 1000;
  const cutoff = Date.now() - sevenDaysMs;
  const recentBookPromos = history.filter((h) => {
    if (h.type !== "book-promo") return false;
    const ts = h.postedAt ? Date.parse(h.postedAt) : NaN;
    return !Number.isNaN(ts) && ts >= cutoff;
  }).length;
  if (recentBookPromos > 1) {
    return [{
      id: "V13", platform: "*", severity: "block",
      message: `book-promo already posted ${recentBookPromos} times in the last 7 days (cap = 1).`,
    }];
  }
  return [];
}

function checkV14_openingRepetition(platform, variant, history) {
  if (!Array.isArray(history) || history.length === 0) {
    return [{
      id: "V14", platform, severity: "skipped",
      message: "History not provided — V14 opening-similarity check skipped.",
    }];
  }
  const text = variant?.text || "";
  const opening = text.split(/\n|[.!?]/)[0] || "";
  const lastFive = history.slice(-5);
  for (const prev of lastFive) {
    const prevOpen =
      (prev?.platforms?.[platform]?.text || prev?.text || "").split(/\n|[.!?]/)[0] || "";
    const sim = openingSimilarity(opening, prevOpen);
    if (sim > 0.7) {
      return [{
        id: "V14", platform, severity: "block",
        message: `Opening too similar to a recent post (overlap ${sim.toFixed(2)}). Previous: "${prevOpen.slice(0, 60)}…"`,
      }];
    }
  }
  return [];
}

function checkV15_privacy(platform, variant) {
  const hay = norm(fullText(variant));
  const hit = PRIVACY_FORBIDDEN.find((p) => hay.includes(p));
  const violations = [];
  if (hit) {
    violations.push({
      id: "V15", platform, severity: "block",
      message: `Forbidden phrase revealing AI origin: "${hit}".`,
    });
  }
  // Exact ages of a specific child, e.g. "my 4-year-old", "mi hijo de 4 años" are OK (generic).
  // But "Sarah's 7-year-old daughter Emma" style = 2 capitalized names + age = too identifying.
  const identifiable = /\b[A-Z][a-z]+\s+[A-Z][a-z]+,? (aged|age|who is|is)?\s*\d{1,2}\b/;
  if (identifiable.test(variant?.text || "")) {
    violations.push({
      id: "V15", platform, severity: "block",
      message: "Mentions a specific named person with an age — possible privacy leak.",
    });
  }
  return violations;
}

function checkV16_allCaps(platform, variant) {
  const text = variant?.text || "";
  const re = /\b[A-Z]{3,}\b/g;
  const matches = text.match(re) || [];
  const violators = matches.filter((w) => !ALLCAPS_WHITELIST.has(w));
  if (violators.length > 0) {
    return [{
      id: "V16", platform, severity: "block",
      message: `ALL-CAPS word(s) detected: ${violators.slice(0, 3).join(", ")}. Use emphasis sparingly with italics or emoji instead.`,
    }];
  }
  return [];
}

function checkV17_hashtagCount(platform, variant) {
  const range = HASHTAG_RANGE[platform];
  if (!range) return [];
  const count = countHashtags(variant?.hashtags || "");
  const [min, max] = range;
  if (count < min || count > max) {
    return [{
      id: "V17", platform, severity: "block",
      message: `Hashtag count ${count} out of range for ${platform} (expected ${min}-${max}).`,
    }];
  }
  return [];
}

function checkV18_noCta(platform, variant) {
  const text = variant?.text || "";
  const hasQuestion = /\?/.test(text);
  const hasUrl = /https?:\/\//i.test(text);
  const hasLinkInBio = /link in bio|link en bio|enlace en bio/i.test(text);
  const hasTagInvite = /\btag\b.*\bmom|tag her|tag a friend|etiqueta a|menciona a/i.test(text);
  if (!hasQuestion && !hasUrl && !hasLinkInBio && !hasTagInvite) {
    return [{
      id: "V18", platform, severity: "block",
      message: "No call to action (no question, no URL, no 'Link in bio', no tag-invitation).",
    }];
  }
  return [];
}

function checkV19_sampleReviewCitation(platform, variant, type, realCount) {
  if (type !== "community") return [];
  if (typeof realCount !== "number") {
    return [{
      id: "V19", platform, severity: "skipped",
      message: "realGalleryReviewCount not provided — V19 sample-review citation check skipped.",
    }];
  }
  const THRESHOLD = 10; // align with gallery.astro SAMPLE_THRESHOLD
  if (realCount >= THRESHOLD) return [];
  const text = variant?.text || "";
  // Heuristic: a quote + a capitalized first name nearby → probable named citation
  const quotedWithName =
    /"[^"]{15,}"[^.]{0,40}[-—][^.]{0,10}\b[A-Z][a-z]+\b/.test(text) ||
    /\b[A-Z][a-z]+\s+(said|wrote|told us|dice|escribió)\b/.test(text);
  if (quotedWithName) {
    return [{
      id: "V19", platform, severity: "block",
      message: `Community post cites a specific review by name, but only ${realCount} real reviews exist (threshold ${THRESHOLD}). Could be quoting a sample.`,
    }];
  }
  return [];
}

function checkV20_bookPlusAmazonInNonPromo(platform, variant, type) {
  if (type === "book-promo") return [];
  const text = fullText(variant);
  const hasAmazon = extractUrls(text).some(isAmazonUrl);
  // "our X coloring book" or quoted book title followed by Amazon URL
  const namesABook =
    /"[^"]+"\s*(coloring|activity|kids|children)/i.test(text) ||
    /our [a-z ]{3,40}(coloring|activity) book/i.test(text);
  if (hasAmazon && namesABook) {
    return [{
      id: "V20", platform, severity: "block",
      message: "Mentions a specific book + Amazon URL on a non-book-promo post. Move Amazon CTA to book-promo only.",
    }];
  }
  return [];
}

// ─── Warnings (W1-W4) ──────────────────────────────────────────────────────

function warnW1_blueskyLong(variant) {
  const text = fullText(variant);
  if (text.length > 260 && text.length <= BLUESKY_MAX_CHARS) {
    return [{
      id: "W1", platform: "bluesky", severity: "warn",
      message: `Bluesky full text is ${text.length} chars — close to limit, may be cut off with URL facets.`,
    }];
  }
  return [];
}

function warnW2_zeroEmoji(platform, variant) {
  if (countEmojis(fullText(variant)) === 0) {
    return [{
      id: "W2", platform, severity: "warn",
      message: "Post has zero emojis. Allowed, but flagged for variety tracking.",
    }];
  }
  return [];
}

function warnW3_consecutiveSamePillar(type, history) {
  if (!Array.isArray(history) || history.length === 0) return [];
  const last = history[history.length - 1];
  if (last?.type === type) {
    return [{
      id: "W3", platform: "*", severity: "warn",
      message: `Previous post was also type "${type}". Consider alternating pillars.`,
    }];
  }
  return [];
}

function warnW4_bannedOpener(platform, variant) {
  const text = variant?.text || "";
  // From BRAND_VOICE_GUIDE.md — generic ad-speak openers to avoid
  const banned = [
    /^check (it|this) out/i,
    /^attention (parents|moms|all)/i,
    /^hey (parents|moms|everyone)[,!]/i,
    /^introducing our/i,
    /^we are (excited|thrilled|proud) to/i,
    /^¡?atención (padres|mamás|mamas)/i,
  ];
  if (banned.some((r) => r.test(text))) {
    return [{
      id: "W4", platform, severity: "warn",
      message: "Opening line uses a banned ad-speak opener — consider a concrete scene instead.",
    }];
  }
  return [];
}

// ─── Public: validatePost ──────────────────────────────────────────────────

/**
 * Run all V1-V20 + W1-W4 checks on a post.
 *
 * @param {object} post — { concept, platforms: { bluesky, facebook, instagram } }
 * @param {object} ctx  — { type, lang, history?, realGalleryReviewCount? }
 * @returns {{ ok: boolean, violations: Array, warnings: Array, skipped: Array }}
 */
export function validatePost(post, ctx = {}) {
  const violations = [];
  const warnings = [];
  const skipped = [];
  const push = (arr) => {
    for (const v of arr) {
      if (v.severity === "skipped") skipped.push(v);
      else if (v.severity === "warn") warnings.push(v);
      else violations.push(v);
    }
  };

  const { type = "unknown", history, realGalleryReviewCount } = ctx;
  const platforms = post?.platforms || {};

  // Per-platform rules
  for (const platform of ["bluesky", "facebook", "instagram"]) {
    const variant = platforms[platform];
    if (!variant) continue;

    push(checkV1_emojiCount(platform, variant));
    push(checkV2_urgency(platform, variant));
    push(checkV3_peanutsFromReviews(platform, variant));
    push(checkV4_ticketsFromShares(platform, variant));
    push(checkV5_nonexistentFeature(platform, variant));
    push(checkV6_shareAsImage(platform, variant));
    push(checkV9_amazonInNonBookPromo(platform, variant, type));
    push(checkV10_amazonAsPrimaryCta(platform, variant, type));
    push(checkV11_utmsMissing(platform, variant));
    push(checkV12_brandHashtag(platform, variant));
    push(checkV14_openingRepetition(platform, variant, history));
    push(checkV15_privacy(platform, variant));
    push(checkV16_allCaps(platform, variant));
    push(checkV17_hashtagCount(platform, variant));
    push(checkV18_noCta(platform, variant));
    push(checkV19_sampleReviewCitation(platform, variant, type, realGalleryReviewCount));
    push(checkV20_bookPlusAmazonInNonPromo(platform, variant, type));

    // Platform-specific
    if (platform === "instagram") push(checkV7_instagramUrl(variant));
    if (platform === "bluesky") {
      push(checkV8_blueskyLength(variant));
      push(warnW1_blueskyLong(variant));
    }

    // Warnings
    push(warnW2_zeroEmoji(platform, variant));
    push(warnW4_bannedOpener(platform, variant));
  }

  // Global rules (not per-platform)
  push(checkV13_bookPromoFrequency(type, history));
  push(warnW3_consecutiveSamePillar(type, history));

  return {
    ok: violations.length === 0,
    violations,
    warnings,
    skipped,
    summary: {
      blocked: violations.length,
      warned: warnings.length,
      skippedChecks: skipped.length,
    },
  };
}

/**
 * Format a validation result as a human-readable report.
 */
export function formatReport(result) {
  const lines = [];
  const { ok, violations, warnings, skipped } = result;
  lines.push(ok ? "✅ PASS — post is publishable." : `❌ BLOCKED — ${violations.length} violation(s).`);
  if (violations.length) {
    lines.push("");
    lines.push("Violations:");
    for (const v of violations) lines.push(`  [${v.id}] (${v.platform}) ${v.message}`);
  }
  if (warnings.length) {
    lines.push("");
    lines.push("Warnings:");
    for (const w of warnings) lines.push(`  [${w.id}] (${w.platform}) ${w.message}`);
  }
  if (skipped.length) {
    lines.push("");
    lines.push("Skipped (context-dependent):");
    for (const s of skipped) lines.push(`  [${s.id}] ${s.message}`);
  }
  return lines.join("\n");
}

// ─── CLI ───────────────────────────────────────────────────────────────────

function parseArgs(argv) {
  const opts = { file: null, stdin: false, type: "unknown", lang: "en", noUtmInject: false };
  for (let i = 0; i < argv.length; i++) {
    switch (argv[i]) {
      case "--file": opts.file = argv[++i]; break;
      case "--stdin": opts.stdin = true; break;
      case "--type": opts.type = argv[++i]; break;
      case "--lang": opts.lang = argv[++i]; break;
      case "--no-utm-inject": opts.noUtmInject = true; break;
    }
  }
  return opts;
}

async function readStdin() {
  return new Promise((resolve, reject) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => { data += chunk; });
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", reject);
  });
}

const isMain =
  import.meta.url === `file://${process.argv[1]}` ||
  import.meta.url.endsWith(process.argv[1]?.replace(/\\/g, "/") || "");

if (isMain) {
  const opts = parseArgs(process.argv.slice(2));
  const raw = opts.file
    ? readFileSync(opts.file, "utf8")
    : opts.stdin
      ? await readStdin()
      : null;

  if (!raw) {
    console.error("Usage: node validate-post.mjs --file <path> --type <type> --lang <lang>");
    console.error("   or: node validate-post.mjs --stdin --type <type> --lang <lang> < post.json");
    process.exit(2);
  }

  let post;
  try {
    post = JSON.parse(raw);
  } catch (err) {
    console.error(`Invalid JSON: ${err.message}`);
    process.exit(2);
  }

  if (!opts.noUtmInject) injectUtms(post, { type: opts.type, lang: opts.lang });

  const result = validatePost(post, { type: opts.type, lang: opts.lang });
  console.log(formatReport(result));
  process.exit(result.ok ? 0 : 1);
}
