function makeFact({
  slug,
  postId,
  tags,
  enTitle,
  esTitle,
  enSummary,
  esSummary,
  enHeading,
  esHeading,
  enFact,
  esFact,
  enPrompt,
  esPrompt,
}) {
  return {
    slug,
    postId,
    tags,
    en: {
      title: enTitle,
      summary: enSummary,
      body: `## ${enHeading}

${enFact}

### Color & Discover 🎨

${enPrompt}`,
    },
    es: {
      title: esTitle,
      summary: esSummary,
      body: `## ${esHeading}

${esFact}

### Colorea y Descubre 🎨

${esPrompt}`,
    },
  };
}

const facts = [
  // ── Space (3) ───────────────────────────────────────
  makeFact({
    slug: "fun-fact-neutron-star-teaspoon-heavy",
    postId: "fun-fact-neutron-star-density",
    tags: ["fun-fact", "space", "science"],
    enTitle: "Did You Know? A Teaspoon of a Neutron Star Would Be Incredibly Heavy!",
    esTitle: "¿Sabías Que? ¡Una Cucharadita de una Estrella de Neutrones Sería Increíblemente Pesada!",
    enSummary: "Neutron stars are so dense that one tiny teaspoon of their material would weigh as much as all humans on Earth together.",
    esSummary: "Las estrellas de neutrones son tan densas que una cucharadita de su material pesaría tanto como todos los humanos de la Tierra juntos.",
    enHeading: "Neutron Stars Are Super Dense! ⭐",
    esHeading: "¡Las Estrellas de Neutrones Son Súper Densas! ⭐",
    enFact: "When a giant star explodes, its core can collapse into a neutron star. The matter gets packed so tightly that one teaspoon could weigh as much as all humans on Earth combined.",
    esFact: "Cuando una estrella gigante explota, su núcleo puede colapsar y convertirse en una estrella de neutrones. La materia queda tan comprimida que una sola cucharadita podría pesar tanto como todos los humanos de la Tierra juntos.",
    enPrompt: "Draw a tiny teaspoon next to a giant space scale. Ask your kids: \"How can something so small be so heavy?\"",
    esPrompt: "Dibuja una cucharadita pequeñita junto a una balanza espacial gigante. Pregúntales a tus peques: \"¿Cómo puede algo tan pequeño ser tan pesado?\"",
  }),
  makeFact({
    slug: "fun-fact-mercury-fastest-planet",
    postId: "fun-fact-mercury-orbit-speed",
    tags: ["fun-fact", "space", "science"],
    enTitle: "Did You Know? Mercury Is the Fastest Planet Around the Sun!",
    esTitle: "¿Sabías Que? ¡Mercurio Es el Planeta Más Rápido Alrededor del Sol!",
    enSummary: "Mercury races around the Sun at about 107,000 miles per hour, making it the speed champion of our solar system.",
    esSummary: "Mercurio corre alrededor del Sol a unos 172,000 km por hora, convirtiéndose en el campeón de velocidad del sistema solar.",
    enHeading: "Mercury Is a Space Speedster! ☄️",
    esHeading: "¡Mercurio Es un Velocista Espacial! ☄️",
    enFact: "Mercury is the closest planet to the Sun, and it moves very fast in orbit at about 107,000 miles (172,000 km) per hour.",
    esFact: "Mercurio es el planeta más cercano al Sol y se mueve rapidísimo en su órbita: aproximadamente 172,000 km por hora.",
    enPrompt: "Color Mercury with a trail behind it like a race car in space. Ask: \"If planets had a race, who would win?\"",
    esPrompt: "Colorea Mercurio con una estela detrás, como un auto de carreras en el espacio. Pregunta: \"Si los planetas hicieran una carrera, ¿quién ganaría?\"",
  }),
  makeFact({
    slug: "fun-fact-black-hole-spaghettification",
    postId: "fun-fact-black-hole-stretching",
    tags: ["fun-fact", "space", "science"],
    enTitle: "Did You Know? Black Holes Can Stretch Objects Like Spaghetti!",
    esTitle: "¿Sabías Que? ¡Los Agujeros Negros Pueden Estirar Objetos Como Espagueti!",
    enSummary: "Near a black hole, gravity can stretch objects into long thin shapes. Scientists call this spaghettification.",
    esSummary: "Cerca de un agujero negro, la gravedad puede estirar objetos en formas largas y delgadas. Eso se llama espaguetificación.",
    enHeading: "Black Holes Can Stretch Things! 🕳️",
    esHeading: "¡Los Agujeros Negros Pueden Estirar las Cosas! 🕳️",
    enFact: "A black hole's gravity is extremely strong. If something gets too close, one side can be pulled more than the other and stretched out like spaghetti.",
    esFact: "La gravedad de un agujero negro es extremadamente fuerte. Si algo se acerca demasiado, un lado puede ser jalado más que el otro y estirarse como espagueti.",
    enPrompt: "Draw a black hole with stars curving around it. Ask: \"What shape would a spaceship need to stay safe?\"",
    esPrompt: "Dibuja un agujero negro con estrellas curvándose a su alrededor. Pregunta: \"¿Qué forma debería tener una nave para mantenerse segura?\"",
  }),

  // ── Animals (3) ─────────────────────────────────────
  makeFact({
    slug: "fun-fact-dogs-understand-many-words",
    postId: "fun-fact-dogs-words",
    tags: ["fun-fact", "animals", "pets"],
    enTitle: "Did You Know? Some Dogs Can Learn Around 165 Words!",
    esTitle: "¿Sabías Que? ¡Algunos Perros Pueden Aprender Alrededor de 165 Palabras!",
    enSummary: "Research shows many dogs can understand a surprisingly large vocabulary, similar to a young child in some cases.",
    esSummary: "Investigaciones muestran que muchos perros pueden entender un vocabulario sorprendentemente grande, parecido al de un niño pequeño en algunos casos.",
    enHeading: "Dogs Can Learn Lots of Words! 🐶",
    esHeading: "¡Los Perros Pueden Aprender Muchas Palabras! 🐶",
    enFact: "Many dogs can understand around 165 words or signals, especially when families use clear and repeated commands.",
    esFact: "Muchos perros pueden entender alrededor de 165 palabras o señales, sobre todo cuando la familia usa comandos claros y repetidos.",
    enPrompt: "Color a dog listening to speech bubbles like sit, stay, and play. Ask: \"What words does your pet know?\"",
    esPrompt: "Colorea un perro escuchando globos de diálogo como siéntate, quieto y jugar. Pregunta: \"¿Qué palabras conoce tu mascota?\"",
  }),
  makeFact({
    slug: "fun-fact-cats-share-dna-with-tigers",
    postId: "fun-fact-cats-tiger-dna",
    tags: ["fun-fact", "animals", "science"],
    enTitle: "Did You Know? House Cats Share Most of Their DNA With Tigers!",
    esTitle: "¿Sabías Que? ¡Los Gatos de Casa Comparten Gran Parte de su ADN con los Tigres!",
    enSummary: "Domestic cats and tigers are closely related. House cats share about 95.6% of their DNA with tigers.",
    esSummary: "Los gatos domésticos y los tigres están muy relacionados. Los gatos de casa comparten alrededor del 95.6% de su ADN con los tigres.",
    enHeading: "Your Cat Has Tiger Cousins! 🐱",
    esHeading: "¡Tu Gato Tiene Primos Tigres! 🐱",
    enFact: "Scientists found that house cats share about 95.6% of their DNA with tigers. That helps explain why cats still stalk and pounce like tiny hunters.",
    esFact: "Los científicos descubrieron que los gatos de casa comparten alrededor del 95.6% de su ADN con los tigres. Eso ayuda a explicar por qué todavía acechan y saltan como mini cazadores.",
    enPrompt: "Draw a split picture: a house cat on one side and a tiger on the other. Ask: \"What behaviors do both cats share?\"",
    esPrompt: "Dibuja una escena dividida: un gato de casa de un lado y un tigre del otro. Pregunta: \"¿Qué comportamientos comparten ambos?\"",
  }),
  makeFact({
    slug: "fun-fact-crows-remember-faces",
    postId: "fun-fact-crows-memory",
    tags: ["fun-fact", "animals", "nature"],
    enTitle: "Did You Know? Crows Can Remember Human Faces!",
    esTitle: "¿Sabías Que? ¡Los Cuervos Pueden Recordar Caras Humanas!",
    enSummary: "Crows are very smart birds and can recognize specific people, sometimes remembering faces for years.",
    esSummary: "Los cuervos son aves muy inteligentes y pueden reconocer personas específicas, recordando rostros durante años.",
    enHeading: "Crows Have Great Memory! 🐦",
    esHeading: "¡Los Cuervos Tienen Excelente Memoria! 🐦",
    enFact: "Crows are highly intelligent. They can remember human faces and even share social information with other crows.",
    esFact: "Los cuervos son muy inteligentes. Pueden recordar caras humanas e incluso compartir información social con otros cuervos.",
    enPrompt: "Color a crow on a city lamp post. Ask: \"If crows had a school, what would they teach?\"",
    esPrompt: "Colorea un cuervo en un poste de luz. Pregunta: \"Si los cuervos tuvieran escuela, ¿qué enseñarían?\"",
  }),

  // ── Body (3) ────────────────────────────────────────
  makeFact({
    slug: "fun-fact-saliva-liter-per-day",
    postId: "fun-fact-saliva-daily",
    tags: ["fun-fact", "body", "science"],
    enTitle: "Did You Know? Your Body Makes About a Liter of Saliva a Day!",
    esTitle: "¿Sabías Que? ¡Tu Cuerpo Produce Aproximadamente un Litro de Saliva al Día!",
    enSummary: "Saliva helps us chew, swallow, and begin digestion. Your body makes around one liter every day.",
    esSummary: "La saliva nos ayuda a masticar, tragar y comenzar la digestión. El cuerpo produce alrededor de un litro cada día.",
    enHeading: "Saliva Is a Helpful Superpower! 👅",
    esHeading: "¡La Saliva Es un Súper Ayudante! 👅",
    enFact: "Your salivary glands can produce about one liter of saliva each day. Saliva keeps your mouth moist and helps digestion begin.",
    esFact: "Tus glándulas salivales pueden producir cerca de un litro de saliva al día. La saliva mantiene tu boca húmeda y ayuda a empezar la digestión.",
    enPrompt: "Draw a smiling mouth with tiny helper drops. Ask: \"Why do we need saliva when we eat crackers?\"",
    esPrompt: "Dibuja una boca sonriendo con gotitas ayudantes. Pregunta: \"¿Por qué necesitamos saliva cuando comemos galletas?\"",
  }),
  makeFact({
    slug: "fun-fact-belly-button-bacteria",
    postId: "fun-fact-belly-button-microbiome",
    tags: ["fun-fact", "body", "science"],
    enTitle: "Did You Know? Your Belly Button Has a Tiny Microbe Neighborhood!",
    esTitle: "¿Sabías Que? ¡Tu Ombligo Tiene un Pequeño Vecindario de Microbios!",
    enSummary: "Scientists have found many different bacteria living in belly buttons as part of our normal body microbiome.",
    esSummary: "Los científicos han encontrado muchos tipos de bacterias viviendo en el ombligo como parte normal de nuestro microbioma.",
    enHeading: "Tiny Life Lives on Us! 🔬",
    esHeading: "¡Hay Vida Minúscula en Nosotros! 🔬",
    enFact: "Scientists found that belly buttons can host many kinds of bacteria. Most are harmless and part of our body's natural microbiome.",
    esFact: "Los científicos descubrieron que los ombligos pueden tener muchos tipos de bacterias. La mayoría son inofensivas y parte del microbioma natural.",
    enPrompt: "Color a cartoon magnifying glass looking at a microbe city. Ask: \"What helpful jobs might tiny microbes do?\"",
    esPrompt: "Colorea una lupa viendo una ciudad de microbios. Pregunta: \"¿Qué trabajos útiles podrían hacer los microbios pequeñitos?\"",
  }),
  makeFact({
    slug: "fun-fact-tongue-print-unique",
    postId: "fun-fact-tongue-print",
    tags: ["fun-fact", "body", "science"],
    enTitle: "Did You Know? Your Tongue Pattern Is Unique!",
    esTitle: "¿Sabías Que? ¡El Patrón de tu Lengua es Único!",
    enSummary: "Like fingerprints, each person has a unique pattern on their tongue.",
    esSummary: "Como las huellas dactilares, cada persona tiene un patrón único en la lengua.",
    enHeading: "Your Tongue Is One of a Kind! 👄",
    esHeading: "¡Tu Lengua Es Única! 👄",
    enFact: "The shape and pattern on your tongue are unique to you, just like fingerprints are unique to each person.",
    esFact: "La forma y el patrón de tu lengua son únicos, igual que las huellas dactilares de cada persona.",
    enPrompt: "Draw a silly tongue character with swirls and shapes. Ask: \"If your tongue had a superhero name, what would it be?\"",
    esPrompt: "Dibuja un personaje-lengua divertido con espirales y formas. Pregunta: \"Si tu lengua tuviera nombre de superhéroe, ¿cuál sería?\"",
  }),

  // ── Earth (3) ───────────────────────────────────────
  makeFact({
    slug: "fun-fact-mid-ocean-ridge-longest",
    postId: "fun-fact-mid-ocean-ridge",
    tags: ["fun-fact", "earth", "science"],
    enTitle: "Did You Know? Earth's Longest Mountain Range Is Underwater!",
    esTitle: "¿Sabías Que? ¡La Cadena Montañosa Más Larga de la Tierra Está Bajo el Mar!",
    enSummary: "The Mid-Ocean Ridge stretches for tens of thousands of miles beneath the ocean, making it Earth's longest mountain chain.",
    esSummary: "La Dorsal Mesooceánica se extiende por decenas de miles de millas bajo el océano, siendo la cadena montañosa más larga del planeta.",
    enHeading: "The Longest Mountains Are Under the Sea! 🌍",
    esHeading: "¡Las Montañas Más Largas Están Bajo el Mar! 🌍",
    enFact: "The Mid-Ocean Ridge runs across the seafloor for about 50,000 miles. Most of it is hidden underwater.",
    esFact: "La Dorsal Mesooceánica recorre el fondo del océano por cerca de 50,000 millas. La mayor parte está oculta bajo el agua.",
    enPrompt: "Color an ocean cross-section with mountains below the waves. Ask: \"What else might be hidden on the ocean floor?\"",
    esPrompt: "Colorea un corte del océano con montañas debajo de las olas. Pregunta: \"¿Qué más podría estar escondido en el fondo marino?\"",
  }),
  makeFact({
    slug: "fun-fact-dead-sea-lowest-dry-land",
    postId: "fun-fact-dead-sea-low",
    tags: ["fun-fact", "earth", "science"],
    enTitle: "Did You Know? The Dead Sea Shore Is One of the Lowest Dry Places on Earth!",
    esTitle: "¿Sabías Que? ¡La Orilla del Mar Muerto Es uno de los Lugares Secos Más Bajos de la Tierra!",
    enSummary: "The Dead Sea shoreline sits far below sea level, making it one of the lowest exposed land points on Earth.",
    esSummary: "La orilla del Mar Muerto está muy por debajo del nivel del mar, siendo uno de los puntos de tierra expuesta más bajos del planeta.",
    enHeading: "Super-Low Land on Earth! 🧭",
    esHeading: "¡Tierra Súper Baja en el Planeta! 🧭",
    enFact: "The shore of the Dead Sea is about 1,400 feet (430 m) below sea level, one of the lowest dry spots on Earth.",
    esFact: "La orilla del Mar Muerto está aproximadamente a 1,400 pies (430 m) por debajo del nivel del mar, uno de los lugares secos más bajos de la Tierra.",
    enPrompt: "Draw a giant height chart with mountains up high and the Dead Sea down low. Ask: \"Would you visit the highest or lowest point first?\"",
    esPrompt: "Dibuja una regla gigante de alturas con montañas arriba y el Mar Muerto abajo. Pregunta: \"¿Visitarías primero el punto más alto o el más bajo?\"",
  }),
  makeFact({
    slug: "fun-fact-earth-day-started-1970",
    postId: "fun-fact-earth-day-1970",
    tags: ["fun-fact", "earth", "history"],
    enTitle: "Did You Know? The First Earth Day Was in 1970!",
    esTitle: "¿Sabías Que? ¡El Primer Día de la Tierra Fue en 1970!",
    enSummary: "Earth Day began in 1970 to help people protect nature and care for our planet.",
    esSummary: "El Día de la Tierra comenzó en 1970 para ayudar a proteger la naturaleza y cuidar nuestro planeta.",
    enHeading: "Earth Day Has a Birthday! 🌱",
    esHeading: "¡El Día de la Tierra Tiene Cumpleaños! 🌱",
    enFact: "The first Earth Day was celebrated in 1970. It helped people focus on cleaner air, cleaner water, and habitat protection.",
    esFact: "El primer Día de la Tierra se celebró en 1970. Ayudó a enfocarse en aire más limpio, agua más limpia y protección de hábitats.",
    enPrompt: "Color Earth with hearts, trees, and oceans. Ask: \"What small thing can we do today to help our planet?\"",
    esPrompt: "Colorea la Tierra con corazones, árboles y océanos. Pregunta: \"¿Qué pequeña acción podemos hacer hoy para cuidar el planeta?\"",
  }),

  // ── Ocean (3) ───────────────────────────────────────
  makeFact({
    slug: "fun-fact-blue-whale-largest-animal",
    postId: "fun-fact-blue-whale-largest",
    tags: ["fun-fact", "ocean", "animals"],
    enTitle: "Did You Know? The Blue Whale Is the Largest Animal Ever Known!",
    esTitle: "¿Sabías Que? ¡La Ballena Azul Es el Animal Más Grande Conocido!",
    enSummary: "Blue whales are bigger than any dinosaur we know, making them the largest animals to have lived on Earth.",
    esSummary: "Las ballenas azules son más grandes que cualquier dinosaurio conocido, siendo los animales más grandes que han vivido en la Tierra.",
    enHeading: "Blue Whales Are Giants! 🐋",
    esHeading: "¡Las Ballenas Azules Son Gigantes! 🐋",
    enFact: "The blue whale is the largest animal scientists know of, even larger than the biggest dinosaurs we have discovered.",
    esFact: "La ballena azul es el animal más grande conocido por la ciencia, incluso más grande que los dinosaurios más enormes descubiertos.",
    enPrompt: "Draw a blue whale next to a school bus for size comparison. Ask: \"How many buses long could a whale be?\"",
    esPrompt: "Dibuja una ballena azul junto a un autobús escolar para comparar tamaños. Pregunta: \"¿Cuántos autobuses crees que mediría una ballena?\"",
  }),
  makeFact({
    slug: "fun-fact-sea-otters-hold-hands-sleep",
    postId: "fun-fact-sea-otters-hold-hands",
    tags: ["fun-fact", "ocean", "animals"],
    enTitle: "Did You Know? Sea Otters Sometimes Hold Hands While Sleeping!",
    esTitle: "¿Sabías Que? ¡Las Nutrias Marinas A Veces Se Toman de las Patas Para Dormir!",
    enSummary: "Sea otters can hold paws while floating so they stay close together and do not drift apart.",
    esSummary: "Las nutrias marinas pueden tomarse de las patas mientras flotan para mantenerse juntas y no separarse con la corriente.",
    enHeading: "Sea Otters Sleep as a Team! 🦦",
    esHeading: "¡Las Nutrias Marinas Duermen en Equipo! 🦦",
    enFact: "Sea otters float on their backs when they rest. They may hold paws so ocean currents do not separate them.",
    esFact: "Las nutrias marinas flotan boca arriba cuando descansan. A veces se toman de las patas para que la corriente no las separe.",
    enPrompt: "Color two otters floating together in kelp. Ask: \"Who is your best nap buddy?\"",
    esPrompt: "Colorea dos nutrias flotando juntas entre algas. Pregunta: \"¿Quién sería tu mejor compañero de siesta?\"",
  }),
  makeFact({
    slug: "fun-fact-mariana-trench-fewer-visits-than-moon",
    postId: "fun-fact-mariana-trench-visits",
    tags: ["fun-fact", "ocean", "science"],
    enTitle: "Did You Know? Fewer People Have Visited the Deepest Ocean Point Than the Moon!",
    esTitle: "¿Sabías Que? ¡Menos Personas Han Visitado el Punto Más Profundo del Océano Que la Luna!",
    enSummary: "The Mariana Trench is so deep and difficult to reach that very few people have visited its deepest area.",
    esSummary: "La Fosa de las Marianas es tan profunda y difícil de alcanzar que muy pocas personas han visitado su zona más profunda.",
    enHeading: "The Deep Ocean Is Hard to Reach! 🌊",
    esHeading: "¡El Océano Profundo Es Muy Difícil de Alcanzar! 🌊",
    enFact: "The Mariana Trench is the deepest known part of the ocean. Reaching the bottom is so hard that very few people have gone there.",
    esFact: "La Fosa de las Marianas es la parte conocida más profunda del océano. Llegar al fondo es tan complicado que muy pocas personas lo han logrado.",
    enPrompt: "Draw ocean layers from sunlight to total darkness. Ask: \"What creature might live at the very bottom?\"",
    esPrompt: "Dibuja capas del océano, desde la luz del sol hasta la oscuridad total. Pregunta: \"¿Qué criatura crees que vive en el fondo más profundo?\"",
  }),

  // ── Food & Plants (3) ───────────────────────────────
  makeFact({
    slug: "fun-fact-cucumber-ninety-five-percent-water",
    postId: "fun-fact-cucumber-water",
    tags: ["fun-fact", "food", "plants"],
    enTitle: "Did You Know? Cucumbers Are About 95% Water!",
    esTitle: "¿Sabías Que? ¡Los Pepinos Son Aproximadamente 95% Agua!",
    enSummary: "Cucumbers are mostly water, which is why they feel crisp and refreshing.",
    esSummary: "Los pepinos están formados casi totalmente por agua, por eso se sienten frescos y crujientes.",
    enHeading: "Cucumbers Are Super Hydrating! 🥒",
    esHeading: "¡El Pepino Hidrata Muchísimo! 🥒",
    enFact: "A cucumber is about 95% water. That is one reason cucumber slices feel cool, crunchy, and refreshing.",
    esFact: "Un pepino tiene alrededor de 95% de agua. Por eso las rodajas de pepino se sienten frescas, crujientes y refrescantes.",
    enPrompt: "Color a cucumber superhero with a water-drop cape. Ask: \"What other foods feel extra juicy?\"",
    esPrompt: "Colorea un pepino superhéroe con capa de gota de agua. Pregunta: \"¿Qué otros alimentos te parecen súper jugosos?\"",
  }),
  makeFact({
    slug: "fun-fact-cranberries-bounce-when-ripe",
    postId: "fun-fact-cranberries-bounce",
    tags: ["fun-fact", "food", "science"],
    enTitle: "Did You Know? Ripe Cranberries Can Bounce!",
    esTitle: "¿Sabías Que? ¡Los Arándanos Rojos Maduros Pueden Rebotar!",
    enSummary: "Cranberries have tiny air pockets, so ripe ones can bounce and float.",
    esSummary: "Los arándanos rojos tienen pequeñas bolsas de aire, por eso los maduros pueden rebotar y flotar.",
    enHeading: "Cranberries Pass a Bounce Test! 🫐",
    esHeading: "¡Los Arándanos Rojos Pasan una Prueba de Rebote! 🫐",
    enFact: "Ripe cranberries have tiny air spaces inside. That helps them bounce and also float in water.",
    esFact: "Los arándanos rojos maduros tienen pequeñas bolsas de aire. Eso les ayuda a rebotar y también a flotar en el agua.",
    enPrompt: "Draw cranberries bouncing like mini balls. Ask: \"What fruit test would you invent at home?\"",
    esPrompt: "Dibuja arándanos rebotando como mini pelotas. Pregunta: \"¿Qué prueba divertida inventarías para otra fruta?\"",
  }),
  makeFact({
    slug: "fun-fact-most-wasabi-is-horseradish",
    postId: "fun-fact-wasabi-horseradish",
    tags: ["fun-fact", "food", "plants"],
    enTitle: "Did You Know? Most Wasabi Is Actually Horseradish Mix!",
    esTitle: "¿Sabías Que? ¡La Mayoría del Wasabi Es en Realidad una Mezcla con Rábano Picante!",
    enSummary: "Real wasabi is hard to grow, so many products use horseradish plus green coloring.",
    esSummary: "El wasabi real es difícil de cultivar, por eso muchos productos usan rábano picante con colorante verde.",
    enHeading: "Wasabi Has a Surprise! 🍣",
    esHeading: "¡El Wasabi Tiene una Sorpresa! 🍣",
    enFact: "Real wasabi is difficult to cultivate. Many wasabi pastes are mostly horseradish with green coloring.",
    esFact: "El wasabi auténtico es difícil de cultivar. Muchas pastas de wasabi son principalmente rábano picante con colorante verde.",
    enPrompt: "Color a sushi plate with labels for ingredients. Ask: \"What other foods have surprising ingredients?\"",
    esPrompt: "Colorea un plato de sushi con etiquetas de ingredientes. Pregunta: \"¿Qué otros alimentos crees que tienen ingredientes sorpresa?\"",
  }),

  // ── Machines & Inventions (3) ───────────────────────
  makeFact({
    slug: "fun-fact-chainsaw-originally-medical-tool",
    postId: "fun-fact-chainsaw-medical-origin",
    tags: ["fun-fact", "machines", "inventions", "history"],
    enTitle: "Did You Know? Early Chainsaws Were First Used for Medical Procedures!",
    esTitle: "¿Sabías Que? ¡Las Primeras Motosierras se Usaron Primero en Procedimientos Médicos!",
    enSummary: "Long before forestry use, early chainsaw designs were developed for specific medical operations.",
    esSummary: "Mucho antes de usarse en bosques, los primeros diseños de motosierra se crearon para operaciones médicas específicas.",
    enHeading: "The First Chainsaw Had a Different Job! 🛠️",
    esHeading: "¡La Primera Motosierra Tenía Otro Trabajo! 🛠️",
    enFact: "The earliest chainsaw design was created for medical use, not tree cutting. Later, engineers adapted chain mechanisms for forestry tools.",
    esFact: "El diseño más temprano de motosierra se creó para uso médico, no para cortar árboles. Después, se adaptó para herramientas forestales.",
    enPrompt: "Draw a timeline with medical tool first and forest tool later. Ask: \"What invention changed jobs over time?\"",
    esPrompt: "Dibuja una línea del tiempo con herramienta médica primero y herramienta de bosque después. Pregunta: \"¿Qué invento cambió de función con los años?\"",
  }),
  makeFact({
    slug: "fun-fact-first-computer-mouse-was-wood",
    postId: "fun-fact-wooden-computer-mouse",
    tags: ["fun-fact", "machines", "inventions"],
    enTitle: "Did You Know? The First Computer Mouse Was Made of Wood!",
    esTitle: "¿Sabías Que? ¡El Primer Mouse de Computadora Era de Madera!",
    enSummary: "The original computer mouse prototype looked like a small wooden box with wheels.",
    esSummary: "El prototipo original del mouse parecía una pequeña cajita de madera con ruedas.",
    enHeading: "The First Mouse Was Wooden! 🖱️",
    esHeading: "¡El Primer Mouse Era de Madera! 🖱️",
    enFact: "The first computer mouse prototype from the 1960s was made of wood and looked very different from modern mice.",
    esFact: "El primer prototipo de mouse de computadora de los años 60 estaba hecho de madera y se veía muy distinto a los actuales.",
    enPrompt: "Color an old wooden mouse next to a modern one. Ask: \"What gadget today might look funny in 50 years?\"",
    esPrompt: "Colorea un mouse antiguo de madera junto a uno moderno. Pregunta: \"¿Qué aparato de hoy crees que se verá raro en 50 años?\"",
  }),
  makeFact({
    slug: "fun-fact-real-computer-bug-was-moth",
    postId: "fun-fact-computer-bug-moth",
    tags: ["fun-fact", "machines", "inventions", "history"],
    enTitle: "Did You Know? A Real Moth Helped Popularize the Term Computer Bug!",
    esTitle: "¿Sabías Que? ¡Una Polilla Real Ayudó a Popularizar el Término Bug en Computación!",
    enSummary: "In 1947, engineers found a moth in a computer relay, and the story helped spread the word bug.",
    esSummary: "En 1947, ingenieros encontraron una polilla en un relé de computadora, y esa historia ayudó a difundir la palabra bug.",
    enHeading: "A Real Bug in a Computer! 💻",
    esHeading: "¡Un Insecto Real en una Computadora! 💻",
    enFact: "In 1947, engineers found a moth inside a relay of an early computer. That famous story helped popularize the word bug for tech problems.",
    esFact: "En 1947, ingenieros encontraron una polilla dentro de un relé de una computadora temprana. Esa historia ayudó a popularizar la palabra bug para problemas técnicos.",
    enPrompt: "Draw a detective moth with a magnifying glass in a computer lab. Ask: \"If you found a code bug, what would you check first?\"",
    esPrompt: "Dibuja una polilla detective con lupa en un laboratorio de computación. Pregunta: \"Si encontraras un bug en código, ¿qué revisarías primero?\"",
  }),

  // ── Colors & Art (3) ────────────────────────────────
  makeFact({
    slug: "fun-fact-eyes-see-ten-million-colors",
    postId: "fun-fact-eyes-ten-million-colors",
    tags: ["fun-fact", "colors", "science"],
    enTitle: "Did You Know? Human Eyes Can Distinguish Millions of Colors!",
    esTitle: "¿Sabías Que? ¡Los Ojos Humanos Pueden Distinguir Millones de Colores!",
    enSummary: "Our visual system can detect around ten million color variations under good conditions.",
    esSummary: "Nuestro sistema visual puede detectar alrededor de diez millones de variaciones de color en buenas condiciones.",
    enHeading: "Your Eyes Are Color Experts! 🌈",
    esHeading: "¡Tus Ojos Son Expertos en Color! 🌈",
    enFact: "Human eyes can tell apart roughly 10 million color shades. That is why sunsets and rainbows can look so rich and detailed.",
    esFact: "Los ojos humanos pueden diferenciar aproximadamente 10 millones de tonos. Por eso los atardeceres y arcoíris se ven tan ricos en detalles.",
    enPrompt: "Make a mini gradient from light to dark. Ask: \"Which two colors look almost the same to you?\"",
    esPrompt: "Haz un mini degradado de claro a oscuro. Pregunta: \"¿Qué dos colores te parecen casi iguales?\"",
  }),
  makeFact({
    slug: "fun-fact-egyptian-blue-first-synthetic-pigment",
    postId: "fun-fact-egyptian-blue-pigment",
    tags: ["fun-fact", "colors", "art", "history"],
    enTitle: "Did You Know? Egyptian Blue Was One of the First Man-Made Pigments!",
    esTitle: "¿Sabías Que? ¡El Azul Egipcio Fue uno de los Primeros Pigmentos Hechos por Humanos!",
    enSummary: "Ancient makers created Egyptian Blue thousands of years ago, one of the earliest synthetic pigments in history.",
    esSummary: "Los artesanos antiguos crearon el Azul Egipcio hace miles de años, uno de los primeros pigmentos sintéticos de la historia.",
    enHeading: "Ancient Artists Made Their Own Blue! 🎨",
    esHeading: "¡Los Artistas Antiguos Fabricaban su Propio Azul! 🎨",
    enFact: "Egyptian Blue was one of the earliest human-made pigments. Ancient craftspeople mixed minerals and heat to create this vivid color.",
    esFact: "El Azul Egipcio fue uno de los primeros pigmentos fabricados por humanos. Los artesanos mezclaban minerales y calor para crear este color intenso.",
    enPrompt: "Color an ancient mural using strong blue patterns. Ask: \"If you invented a new color, what would you name it?\"",
    esPrompt: "Colorea un mural antiguo con patrones azules intensos. Pregunta: \"Si inventaras un color nuevo, ¿cómo lo llamarías?\"",
  }),
  makeFact({
    slug: "fun-fact-oranges-can-stay-green-in-tropics",
    postId: "fun-fact-green-oranges-tropics",
    tags: ["fun-fact", "colors", "food", "science"],
    enTitle: "Did You Know? Ripe Oranges Can Stay Green in Warm Climates!",
    esTitle: "¿Sabías Que? ¡Las Naranjas Maduras Pueden Seguir Verdes en Climas Cálidos!",
    enSummary: "In tropical places, oranges may stay green outside even when they are fully ripe inside.",
    esSummary: "En zonas tropicales, las naranjas pueden verse verdes por fuera aunque estén maduras por dentro.",
    enHeading: "Orange Fruit, Green Peel! 🍊",
    esHeading: "¡Fruta Naranja, Cáscara Verde! 🍊",
    enFact: "In warm tropical climates, ripe oranges can keep a green peel because temperatures do not drop enough to remove chlorophyll.",
    esFact: "En climas tropicales cálidos, una naranja madura puede mantener la cáscara verde porque la temperatura no baja lo suficiente para perder la clorofila.",
    enPrompt: "Draw two oranges: one orange peel and one green peel. Ask: \"How can we know fruit is ripe besides color?\"",
    esPrompt: "Dibuja dos naranjas: una con cáscara naranja y otra verde. Pregunta: \"¿Cómo sabemos si una fruta está madura además del color?\"",
  }),

  // ── History & Language (3) ──────────────────────────
  makeFact({
    slug: "fun-fact-ketchup-sold-as-medicine",
    postId: "fun-fact-ketchup-medicine",
    tags: ["fun-fact", "history", "food"],
    enTitle: "Did You Know? Ketchup Was Once Sold as Medicine!",
    esTitle: "¿Sabías Que? ¡El Kétchup Antes se Vendía Como Medicina!",
    enSummary: "In the 1800s, some sellers promoted tomato ketchup as a health remedy.",
    esSummary: "En el siglo XIX, algunos vendedores promocionaban el kétchup de tomate como remedio de salud.",
    enHeading: "Ketchup Had a Weird History! 🍅",
    esHeading: "¡El Kétchup Tiene una Historia Rara! 🍅",
    enFact: "In the 1830s, some people marketed tomato ketchup as medicine for stomach problems. Today, we mostly use it on food.",
    esFact: "En la década de 1830, algunas personas promocionaban el kétchup de tomate como medicina para el estómago. Hoy lo usamos más en comidas.",
    enPrompt: "Color a vintage ketchup bottle with an old-time label. Ask: \"What everyday food might have a surprising history too?\"",
    esPrompt: "Colorea una botella vintage de kétchup con etiqueta antigua. Pregunta: \"¿Qué comida diaria crees que también tuvo una historia sorprendente?\"",
  }),
  makeFact({
    slug: "fun-fact-oxford-older-than-aztec-empire",
    postId: "fun-fact-oxford-older-than-aztec",
    tags: ["fun-fact", "history", "language"],
    enTitle: "Did You Know? Oxford University Is Older Than the Aztec Empire!",
    esTitle: "¿Sabías Que? ¡La Universidad de Oxford Es Más Antigua Que el Imperio Azteca!",
    enSummary: "Teaching began at Oxford around 1096, long before the Aztec capital was founded in 1325.",
    esSummary: "La enseñanza en Oxford empezó alrededor de 1096, mucho antes de que se fundara la capital azteca en 1325.",
    enHeading: "A Very Old University! 📚",
    esHeading: "¡Una Universidad Muy Antigua! 📚",
    enFact: "Teaching at Oxford started around 1096. The Aztec capital city Tenochtitlán was founded later, in 1325.",
    esFact: "La enseñanza en Oxford comenzó alrededor de 1096. La capital azteca Tenochtitlán se fundó después, en 1325.",
    enPrompt: "Draw two timeline cards: Oxford and Aztec Empire. Ask: \"Which old place would you visit first in a time machine?\"",
    esPrompt: "Dibuja dos tarjetas en línea del tiempo: Oxford e Imperio Azteca. Pregunta: \"¿A qué lugar antiguo viajarías primero en una máquina del tiempo?\"",
  }),
  makeFact({
    slug: "fun-fact-popsicle-invented-by-kid",
    postId: "fun-fact-popsicle-invented-by-kid",
    tags: ["fun-fact", "history", "food"],
    enTitle: "Did You Know? The Popsicle Was Invented by an 11-Year-Old!",
    esTitle: "¿Sabías Que? ¡La Paleta Helada Fue Inventada por un Niño de 11 Años!",
    enSummary: "A boy accidentally left a flavored drink outside in the cold with a stick, and a frozen treat idea was born.",
    esSummary: "Un niño dejó accidentalmente una bebida saborizada en el frío con un palito, y así nació una idea de postre helado.",
    enHeading: "A Kid Invented a Frozen Treat! 🍧",
    esHeading: "¡Un Niño Inventó un Postre Helado! 🍧",
    enFact: "In 1905, 11-year-old Frank Epperson accidentally left a drink outside overnight with a stick in it. It froze and inspired the Popsicle.",
    esFact: "En 1905, Frank Epperson, de 11 años, dejó una bebida afuera durante la noche con un palito dentro. Se congeló y eso inspiró la paleta helada.",
    enPrompt: "Color your dream popsicle with wild flavor stripes. Ask: \"What new frozen flavor would you invent?\"",
    esPrompt: "Colorea tu paleta soñada con franjas de sabores locos. Pregunta: \"¿Qué sabor nuevo de paleta inventarías?\"",
  }),

  // ── World Records (3) ───────────────────────────────
  makeFact({
    slug: "fun-fact-burj-khalifa-tallest-building",
    postId: "fun-fact-burj-khalifa-record",
    tags: ["fun-fact", "records", "world-records"],
    enTitle: "Did You Know? Burj Khalifa Holds the Height Record for Buildings!",
    esTitle: "¿Sabías Que? ¡El Burj Khalifa Tiene el Récord de Altura Entre los Edificios!",
    enSummary: "The Burj Khalifa in Dubai is the tallest building in the world, reaching over 2,700 feet.",
    esSummary: "El Burj Khalifa en Dubái es el edificio más alto del mundo y supera los 2,700 pies de altura.",
    enHeading: "A Sky-High Record! 🏙️",
    esHeading: "¡Un Récord que Toca el Cielo! 🏙️",
    enFact: "The Burj Khalifa is the tallest building on Earth, around 2,716 feet (828 m) tall.",
    esFact: "El Burj Khalifa es el edificio más alto de la Tierra, con unos 2,716 pies (828 m) de altura.",
    enPrompt: "Draw the Burj Khalifa next to shorter buildings in rainbow colors. Ask: \"If you designed a super-tall tower, what would be at the top?\"",
    esPrompt: "Dibuja el Burj Khalifa junto a edificios más bajos con colores de arcoíris. Pregunta: \"Si diseñaras una torre súper alta, ¿qué pondrías arriba?\"",
  }),
  makeFact({
    slug: "fun-fact-nile-longest-river-record",
    postId: "fun-fact-nile-longest-river",
    tags: ["fun-fact", "records", "world-records"],
    enTitle: "Did You Know? The Nile Is One of the Longest River Systems in the World!",
    esTitle: "¿Sabías Que? ¡El Nilo Es uno de los Sistemas de Río Más Largos del Mundo!",
    enSummary: "The Nile stretches for thousands of miles across Africa and is famous for being one of Earth's longest rivers.",
    esSummary: "El Nilo se extiende por miles de millas a través de África y es famoso por ser uno de los ríos más largos de la Tierra.",
    enHeading: "A River Record! 🛶",
    esHeading: "¡Récord de Río! 🛶",
    enFact: "The Nile is known as one of the longest river systems in the world, stretching across multiple countries in Africa.",
    esFact: "El Nilo es conocido como uno de los sistemas de río más largos del mundo y recorre varios países de África.",
    enPrompt: "Color a map path of a giant river from mountains to sea. Ask: \"What animals might live along a super-long river?\"",
    esPrompt: "Colorea en un mapa el recorrido de un río gigante desde montañas hasta el mar. Pregunta: \"¿Qué animales vivirían cerca de un río tan largo?\"",
  }),
  makeFact({
    slug: "fun-fact-rubiks-cube-speed-record",
    postId: "fun-fact-rubiks-cube-record",
    tags: ["fun-fact", "records", "world-records"],
    enTitle: "Did You Know? The Rubik's Cube Speed Record Is Just a Few Seconds!",
    esTitle: "¿Sabías Que? ¡El Récord de Velocidad del Cubo de Rubik Es de Solo Unos Segundos!",
    enSummary: "Top speedcubers can solve a Rubik's Cube in barely over three seconds.",
    esSummary: "Los mejores speedcubers pueden resolver un Cubo de Rubik en apenas un poco más de tres segundos.",
    enHeading: "Color Puzzle at Lightning Speed! 🧩",
    esHeading: "¡Rompecabezas de Color a Velocidad de Rayo! 🧩",
    enFact: "World-class speedcubers can solve a Rubik's Cube in just over 3 seconds. That takes incredible memory, practice, and focus.",
    esFact: "Los mejores speedcubers del mundo pueden resolver un Cubo de Rubik en poco más de 3 segundos. Requiere memoria increíble, práctica y concentración.",
    enPrompt: "Draw a cube with each side in a new color pattern. Ask: \"If you made your own puzzle cube, what colors would you choose?\"",
    esPrompt: "Dibuja un cubo con un patrón nuevo de colores en cada lado. Pregunta: \"Si crearas tu propio cubo, ¿qué colores elegirías?\"",
  }),
];

export default {
  batch: 1,
  name: "Batch 01 — Foundation + World Records kickoff",
  description:
    "Adds 30 bilingual fun facts from under-covered topics and launches the new world-records category.",
  facts,
};
