function makeFact({
  slug,
  postId,
  tags,
  enTitle,
  esTitle,
  enSummary,
  esSummary,
  enHeading,
  esHeading,
  enFact,
  esFact,
  enPrompt,
  esPrompt,
}) {
  return {
    slug,
    postId,
    tags,
    en: {
      title: enTitle,
      summary: enSummary,
      body: `## ${enHeading}

${enFact}

### Color & Discover 🎨

${enPrompt}`,
    },
    es: {
      title: esTitle,
      summary: esSummary,
      body: `## ${esHeading}

${esFact}

### Colorea y Descubre 🎨

${esPrompt}`,
    },
  };
}

const facts = [
  // ── Space (3) ───────────────────────────────────────
  makeFact({
    slug: "fun-fact-olympus-mons-largest-volcano",
    postId: "fun-fact-olympus-mons-record",
    tags: ["fun-fact", "space", "science", "records"],
    enTitle: "Did You Know? Mars Has the Largest Volcano in the Solar System!",
    esTitle: "¿Sabías Que? ¡Marte Tiene el Volcán Más Grande del Sistema Solar!",
    enSummary: "Olympus Mons on Mars is a giant shield volcano that is much taller than Mount Everest.",
    esSummary: "Olympus Mons en Marte es un volcán escudo gigante mucho más alto que el Monte Everest.",
    enHeading: "A Giant Volcano on Mars! 🌋",
    esHeading: "¡Un Volcán Gigante en Marte! 🌋",
    enFact: "Olympus Mons is an enormous volcano on Mars. It rises about 13.6 miles (22 km) high, making it the tallest known volcano in the solar system.",
    esFact: "Olympus Mons es un volcán enorme en Marte. Mide cerca de 13.6 millas (22 km) de alto, por eso se considera el volcán conocido más alto del sistema solar.",
    enPrompt: "Draw Olympus Mons with tiny astronaut explorers at the bottom. Ask: How small would you look next to a space volcano?",
    esPrompt: "Dibuja Olympus Mons con astronautas pequeñitos en la base. Pregunta: ¿Qué tan pequeño te verías junto a un volcán espacial?",
  }),
  makeFact({
    slug: "fun-fact-jupiter-great-red-spot-storm",
    postId: "fun-fact-jupiter-red-spot",
    tags: ["fun-fact", "space", "science"],
    enTitle: "Did You Know? Jupiter Has a Storm Bigger Than Earth!",
    esTitle: "¿Sabías Que? ¡Júpiter Tiene una Tormenta Más Grande Que la Tierra!",
    enSummary: "Jupiter's Great Red Spot is a huge storm that has been watched for hundreds of years.",
    esSummary: "La Gran Mancha Roja de Júpiter es una tormenta enorme observada durante cientos de años.",
    enHeading: "A Super-Sized Space Storm! 🌀",
    esHeading: "¡Una Tormenta Espacial Gigante! 🌀",
    enFact: "Jupiter's Great Red Spot is a giant spinning storm. It is wider than Earth and has been observed by astronomers for centuries.",
    esFact: "La Gran Mancha Roja de Júpiter es una tormenta giratoria gigante. Es más ancha que la Tierra y los astrónomos la han observado durante siglos.",
    enPrompt: "Color Jupiter with swirling stripes and a big red oval. Ask: What colors would your own planet storm have?",
    esPrompt: "Colorea Júpiter con franjas en espiral y un gran óvalo rojo. Pregunta: ¿Qué colores tendría tu propia tormenta planetaria?",
  }),
  makeFact({
    slug: "fun-fact-mercury-long-solar-day",
    postId: "fun-fact-mercury-solar-day",
    tags: ["fun-fact", "space", "science"],
    enTitle: "Did You Know? One Sunrise on Mercury Takes a Very Long Time!",
    esTitle: "¿Sabías Que? ¡Un Amanecer en Mercurio Tarda Muchísimo!",
    enSummary: "Because Mercury spins slowly and orbits quickly, one solar day there lasts about 176 Earth days.",
    esSummary: "Como Mercurio gira lento y orbita rápido, un día solar allí dura unos 176 días terrestres.",
    enHeading: "Mercury Has Super Long Days! ☀️",
    esHeading: "¡Mercurio Tiene Días Súper Largos! ☀️",
    enFact: "Mercury races around the Sun but spins slowly. From one sunrise to the next, a solar day on Mercury lasts about 176 Earth days.",
    esFact: "Mercurio corre alrededor del Sol, pero gira lentamente. De un amanecer al siguiente, un día solar en Mercurio dura cerca de 176 días terrestres.",
    enPrompt: "Draw a calendar next to Mercury with many pages flying by. Ask: What would you do during the longest day ever?",
    esPrompt: "Dibuja un calendario junto a Mercurio con muchas hojas volando. Pregunta: ¿Qué harías durante el día más largo de todos?",
  }),

  // ── Animals (3) ─────────────────────────────────────
  makeFact({
    slug: "fun-fact-axolotls-regrow-limbs",
    postId: "fun-fact-axolotl-regeneration",
    tags: ["fun-fact", "animals", "science"],
    enTitle: "Did You Know? Axolotls Can Regrow Body Parts!",
    esTitle: "¿Sabías Que? ¡Los Ajolotes Pueden Regenerar Partes del Cuerpo!",
    enSummary: "Axolotls are amazing amphibians that can regrow limbs and even parts of organs.",
    esSummary: "Los ajolotes son anfibios asombrosos que pueden regenerar extremidades e incluso partes de órganos.",
    enHeading: "A Real-Life Regrowth Expert! 🦎",
    esHeading: "¡Un Experto Real en Regeneración! 🦎",
    enFact: "Axolotls can regrow legs, tails, and other tissues after injury. Scientists study them to understand healing and regeneration.",
    esFact: "Los ajolotes pueden regenerar patas, cola y otros tejidos después de una lesión. Los científicos los estudian para entender la curación y la regeneración.",
    enPrompt: "Color an axolotl with feathery pink gills in a clear lake. Ask: What superpower would help animals stay healthy?",
    esPrompt: "Colorea un ajolote con branquias rosadas como plumas en un lago claro. Pregunta: ¿Qué superpoder ayudaría a los animales a estar sanos?",
  }),
  makeFact({
    slug: "fun-fact-hummingbirds-fly-backward",
    postId: "fun-fact-hummingbird-backward-flight",
    tags: ["fun-fact", "animals", "nature"],
    enTitle: "Did You Know? Hummingbirds Can Fly Backward!",
    esTitle: "¿Sabías Que? ¡Los Colibríes Pueden Volar Hacia Atrás!",
    enSummary: "Hummingbirds flap their wings in a special pattern that lets them hover and fly backward.",
    esSummary: "Los colibríes mueven sus alas de una forma especial que les permite quedarse quietos y volar hacia atrás.",
    enHeading: "Tiny Birds With Big Flying Skills! 🐦",
    esHeading: "¡Aves Pequeñas con Grandes Habilidades! 🐦",
    enFact: "Hummingbirds can hover in place and fly backward because their wings move in a figure-eight pattern. That helps them sip nectar from flowers.",
    esFact: "Los colibríes pueden quedarse suspendidos y volar hacia atrás porque sus alas se mueven en forma de ocho. Eso les ayuda a tomar néctar de las flores.",
    enPrompt: "Draw a hummingbird hovering beside bright flowers. Ask: If you could fly backward, where would you zoom first?",
    esPrompt: "Dibuja un colibrí suspendido junto a flores brillantes. Pregunta: Si pudieras volar hacia atrás, ¿a dónde irías primero?",
  }),
  makeFact({
    slug: "fun-fact-octopus-blue-blood",
    postId: "fun-fact-octopus-blue-blood",
    tags: ["fun-fact", "animals", "ocean", "science"],
    enTitle: "Did You Know? Octopuses Have Blue Blood!",
    esTitle: "¿Sabías Que? ¡Los Pulpos Tienen Sangre Azul!",
    enSummary: "Octopus blood looks blue because it uses copper-rich hemocyanin to carry oxygen.",
    esSummary: "La sangre del pulpo se ve azul porque usa hemocianina rica en cobre para transportar oxígeno.",
    enHeading: "Blue Blood Under the Sea! 🐙",
    esHeading: "¡Sangre Azul Bajo el Mar! 🐙",
    enFact: "Octopuses use a copper-based protein called hemocyanin to move oxygen through their bodies. That can make their blood look blue.",
    esFact: "Los pulpos usan una proteína con cobre llamada hemocianina para mover oxígeno por su cuerpo. Por eso su sangre puede verse azul.",
    enPrompt: "Color an octopus in deep-sea blues and purples. Ask: What other ocean animal colors surprise you?",
    esPrompt: "Colorea un pulpo con azules y morados de mar profundo. Pregunta: ¿Qué otros colores de animales marinos te sorprenden?",
  }),

  // ── Body (3) ────────────────────────────────────────
  makeFact({
    slug: "fun-fact-skin-largest-organ",
    postId: "fun-fact-skin-largest-organ",
    tags: ["fun-fact", "body", "science"],
    enTitle: "Did You Know? Skin Is Your Body's Largest Organ!",
    esTitle: "¿Sabías Que? ¡La Piel Es el Órgano Más Grande del Cuerpo!",
    enSummary: "Skin protects your body, helps you feel the world, and is your largest organ.",
    esSummary: "La piel protege tu cuerpo, te ayuda a sentir el mundo y es tu órgano más grande.",
    enHeading: "Your Skin Is a Super Suit! ✋",
    esHeading: "¡Tu Piel Es un Súper Traje! ✋",
    enFact: "Skin is an organ, and it is the largest one you have. It helps protect you, sense temperature, and keep germs out.",
    esFact: "La piel es un órgano, y es el más grande que tienes. Ayuda a protegerte, sentir la temperatura y mantener alejados muchos microbios.",
    enPrompt: "Draw a superhero suit labeled skin power. Ask: What jobs does your skin do every day?",
    esPrompt: "Dibuja un traje de superhéroe llamado poder de la piel. Pregunta: ¿Qué trabajos hace tu piel cada día?",
  }),
  makeFact({
    slug: "fun-fact-heart-beats-hundred-thousand-day",
    postId: "fun-fact-heart-daily-beats",
    tags: ["fun-fact", "body", "science"],
    enTitle: "Did You Know? Your Heart Beats About 100,000 Times a Day!",
    esTitle: "¿Sabías Que? ¡Tu Corazón Late Cerca de 100,000 Veces al Día!",
    enSummary: "A healthy heart works all day and night, beating about 100,000 times daily.",
    esSummary: "Un corazón sano trabaja día y noche, latiendo cerca de 100,000 veces al día.",
    enHeading: "Your Heart Is Always Working! ❤️",
    esHeading: "¡Tu Corazón Siempre Está Trabajando! ❤️",
    enFact: "Your heart keeps blood moving through your body. In one day, it can beat around 100,000 times, even while you sleep.",
    esFact: "Tu corazón mantiene la sangre moviéndose por tu cuerpo. En un día puede latir alrededor de 100,000 veces, incluso mientras duermes.",
    enPrompt: "Color a happy heart with music notes around it. Ask: What activities make your heartbeat faster?",
    esPrompt: "Colorea un corazón feliz con notas musicales alrededor. Pregunta: ¿Qué actividades hacen que tu corazón lata más rápido?",
  }),
  makeFact({
    slug: "fun-fact-ear-smallest-bones",
    postId: "fun-fact-ear-smallest-bones",
    tags: ["fun-fact", "body", "science"],
    enTitle: "Did You Know? The Smallest Bones Are in Your Ear!",
    esTitle: "¿Sabías Que? ¡Los Huesos Más Pequeños Están en tu Oído!",
    enSummary: "Three tiny ear bones help carry sound vibrations so you can hear.",
    esSummary: "Tres huesitos del oído llevan vibraciones de sonido para que puedas escuchar.",
    enHeading: "Tiny Bones Help You Hear! 👂",
    esHeading: "¡Huesitos Diminutos Te Ayudan a Oír! 👂",
    enFact: "The hammer, anvil, and stirrup are tiny bones in the middle ear. The stirrup is the smallest bone in the human body.",
    esFact: "El martillo, el yunque y el estribo son huesitos del oído medio. El estribo es el hueso más pequeño del cuerpo humano.",
    enPrompt: "Draw a giant ear with three tiny helper bones inside. Ask: What sounds do you love hearing most?",
    esPrompt: "Dibuja una oreja gigante con tres huesitos ayudantes dentro. Pregunta: ¿Qué sonidos te encanta escuchar?",
  }),

  // ── Earth (3) ───────────────────────────────────────
  makeFact({
    slug: "fun-fact-antarctica-driest-continent",
    postId: "fun-fact-antarctica-dry-desert",
    tags: ["fun-fact", "earth", "science"],
    enTitle: "Did You Know? Antarctica Is the Driest Continent!",
    esTitle: "¿Sabías Que? ¡La Antártida Es el Continente Más Seco!",
    enSummary: "Even though it is covered in ice, Antarctica gets very little precipitation.",
    esSummary: "Aunque está cubierta de hielo, la Antártida recibe muy poca precipitación.",
    enHeading: "A Frozen Desert! ❄️",
    esHeading: "¡Un Desierto Congelado! ❄️",
    enFact: "Antarctica is icy, but much of it is extremely dry. A desert is defined by low precipitation, not only by heat.",
    esFact: "La Antártida tiene mucho hielo, pero gran parte es extremadamente seca. Un desierto se define por poca precipitación, no solo por calor.",
    enPrompt: "Draw an icy desert with penguins and wind lines. Ask: Can a desert be cold?",
    esPrompt: "Dibuja un desierto helado con pingüinos y líneas de viento. Pregunta: ¿Un desierto puede ser frío?",
  }),
  makeFact({
    slug: "fun-fact-earth-magnetic-field-shield",
    postId: "fun-fact-earth-magnetic-shield",
    tags: ["fun-fact", "earth", "science"],
    enTitle: "Did You Know? Earth Has an Invisible Magnetic Shield!",
    esTitle: "¿Sabías Que? ¡La Tierra Tiene un Escudo Magnético Invisible!",
    enSummary: "Earth's magnetic field helps protect our planet from some charged particles from the Sun.",
    esSummary: "El campo magnético de la Tierra ayuda a proteger el planeta de algunas partículas cargadas del Sol.",
    enHeading: "An Invisible Planet Shield! 🧲",
    esHeading: "¡Un Escudo Planetario Invisible! 🧲",
    enFact: "Earth's magnetic field reaches far into space. It helps guide compasses and protects us from some solar particles.",
    esFact: "El campo magnético de la Tierra se extiende muy lejos en el espacio. Ayuda a orientar brújulas y nos protege de algunas partículas solares.",
    enPrompt: "Color Earth inside a glowing shield with compass arrows. Ask: How would explorers use a compass?",
    esPrompt: "Colorea la Tierra dentro de un escudo brillante con flechas de brújula. Pregunta: ¿Cómo usarían una brújula los exploradores?",
  }),
  makeFact({
    slug: "fun-fact-lightning-hotter-than-sun-surface",
    postId: "fun-fact-lightning-temperature",
    tags: ["fun-fact", "earth", "science"],
    enTitle: "Did You Know? Lightning Can Be Hotter Than the Sun's Surface!",
    esTitle: "¿Sabías Que? ¡Un Rayo Puede Ser Más Caliente Que la Superficie del Sol!",
    enSummary: "A lightning bolt can heat the air around it to temperatures hotter than the Sun's surface.",
    esSummary: "Un rayo puede calentar el aire a temperaturas más altas que la superficie del Sol.",
    enHeading: "A Flash of Super Heat! ⚡",
    esHeading: "¡Un Destello Súper Caliente! ⚡",
    enFact: "Lightning is a burst of electricity. For a brief moment, it can heat nearby air to about 50,000°F (27,700°C).",
    esFact: "Un rayo es una descarga de electricidad. Por un instante puede calentar el aire cercano a unos 50,000°F (27,700°C).",
    enPrompt: "Draw a storm cloud with bright zigzag lightning. Ask: Why should we always go indoors during thunderstorms?",
    esPrompt: "Dibuja una nube de tormenta con rayos brillantes en zigzag. Pregunta: ¿Por qué debemos entrar a casa durante una tormenta eléctrica?",
  }),

  // ── Ocean (3) ───────────────────────────────────────
  makeFact({
    slug: "fun-fact-coral-reefs-are-animals",
    postId: "fun-fact-coral-animals",
    tags: ["fun-fact", "ocean", "animals", "science"],
    enTitle: "Did You Know? Corals Are Animals, Not Plants!",
    esTitle: "¿Sabías Que? ¡Los Corales Son Animales, No Plantas!",
    enSummary: "Coral reefs are built by tiny animals called polyps that live together in colonies.",
    esSummary: "Los arrecifes de coral son construidos por animalitos llamados pólipos que viven en colonias.",
    enHeading: "Tiny Animals Build Reefs! 🪸",
    esHeading: "¡Animalitos Construyen Arrecifes! 🪸",
    enFact: "Corals may look like colorful plants or rocks, but they are animals. Tiny coral polyps build reef structures over time.",
    esFact: "Los corales pueden parecer plantas o rocas de colores, pero son animales. Pequeños pólipos de coral construyen arrecifes con el tiempo.",
    enPrompt: "Color a reef city full of fish and coral polyps. Ask: What would live in your underwater neighborhood?",
    esPrompt: "Colorea una ciudad de arrecife con peces y pólipos de coral. Pregunta: ¿Qué viviría en tu vecindario submarino?",
  }),
  makeFact({
    slug: "fun-fact-moon-pulls-ocean-tides",
    postId: "fun-fact-moon-ocean-tides",
    tags: ["fun-fact", "ocean", "space", "science"],
    enTitle: "Did You Know? The Moon Helps Pull the Ocean Tides!",
    esTitle: "¿Sabías Que? ¡La Luna Ayuda a Mover las Mareas del Océano!",
    enSummary: "The Moon's gravity pulls on Earth's oceans, helping create high and low tides.",
    esSummary: "La gravedad de la Luna atrae los océanos de la Tierra y ayuda a crear mareas altas y bajas.",
    enHeading: "The Moon Moves the Sea! 🌙",
    esHeading: "¡La Luna Mueve el Mar! 🌙",
    enFact: "The Moon's gravity pulls on Earth's water. As Earth turns, ocean places can experience high tide and low tide.",
    esFact: "La gravedad de la Luna atrae el agua de la Tierra. Mientras la Tierra gira, distintos lugares del océano tienen marea alta y marea baja.",
    enPrompt: "Draw the Moon tugging gently on ocean waves. Ask: What would you collect on a beach at low tide?",
    esPrompt: "Dibuja la Luna jalando suavemente las olas del océano. Pregunta: ¿Qué recogerías en la playa con marea baja?",
  }),
  makeFact({
    slug: "fun-fact-giant-kelp-underwater-forests",
    postId: "fun-fact-giant-kelp-forests",
    tags: ["fun-fact", "ocean", "plants", "science"],
    enTitle: "Did You Know? Giant Kelp Can Make Underwater Forests!",
    esTitle: "¿Sabías Que? ¡El Kelp Gigante Puede Formar Bosques Submarinos!",
    enSummary: "Giant kelp grows tall in the ocean and creates shelter for many marine animals.",
    esSummary: "El kelp gigante crece alto en el océano y crea refugio para muchos animales marinos.",
    enHeading: "Forests Under the Waves! 🌿",
    esHeading: "¡Bosques Bajo las Olas! 🌿",
    enFact: "Giant kelp is a type of algae that can grow very tall in cool coastal waters. Kelp forests give fish, otters, and other animals places to hide and hunt.",
    esFact: "El kelp gigante es un tipo de alga que puede crecer muy alto en aguas costeras frías. Los bosques de kelp dan refugio y alimento a peces, nutrias y otros animales.",
    enPrompt: "Color a kelp forest with sea otters weaving between green ribbons. Ask: What animal would you hide in a sea forest?",
    esPrompt: "Colorea un bosque de kelp con nutrias nadando entre cintas verdes. Pregunta: ¿Qué animal esconderías en un bosque marino?",
  }),

  // ── Food & Plants (3) ───────────────────────────────
  makeFact({
    slug: "fun-fact-strawberries-seeds-outside",
    postId: "fun-fact-strawberry-seeds-outside",
    tags: ["fun-fact", "food", "plants", "science"],
    enTitle: "Did You Know? Strawberries Wear Their Seeds on the Outside!",
    esTitle: "¿Sabías Que? ¡Las Fresas Llevan sus Semillas por Fuera!",
    enSummary: "A strawberry's tiny seed-like dots sit on the outside instead of hidden inside.",
    esSummary: "Los puntitos de la fresa están por fuera en lugar de estar escondidos dentro.",
    enHeading: "Seeds on the Outside! 🍓",
    esHeading: "¡Semillas por Fuera! 🍓",
    enFact: "The little dots on a strawberry are tiny fruits called achenes, and each one has a seed inside. That makes strawberries extra unusual.",
    esFact: "Los puntitos de una fresa son frutitos diminutos llamados aquenios, y cada uno tiene una semilla dentro. Eso hace que las fresas sean muy especiales.",
    enPrompt: "Draw a giant strawberry and count the tiny dots. Ask: What pattern would you give a pretend fruit?",
    esPrompt: "Dibuja una fresa gigante y cuenta sus puntitos. Pregunta: ¿Qué patrón le pondrías a una fruta imaginaria?",
  }),
  makeFact({
    slug: "fun-fact-potatoes-grown-in-space",
    postId: "fun-fact-potatoes-space",
    tags: ["fun-fact", "food", "plants", "space", "science"],
    enTitle: "Did You Know? Potatoes Have Been Grown in Space!",
    esTitle: "¿Sabías Que? ¡Se Han Cultivado Papas en el Espacio!",
    enSummary: "Scientists have tested growing potatoes in space to learn about food for future missions.",
    esSummary: "Los científicos han probado cultivar papas en el espacio para estudiar alimentos de futuras misiones.",
    enHeading: "Space Potatoes! 🥔",
    esHeading: "¡Papas Espaciales! 🥔",
    enFact: "Potatoes were among the crops tested in space experiments. Scientists study space gardening to understand how astronauts might grow food on long trips.",
    esFact: "Las papas han sido parte de experimentos de cultivo en el espacio. Los científicos estudian la jardinería espacial para saber cómo los astronautas podrían cultivar alimentos en viajes largos.",
    enPrompt: "Color a potato plant inside a spaceship greenhouse. Ask: What food would you grow on Mars?",
    esPrompt: "Colorea una planta de papa dentro de un invernadero espacial. Pregunta: ¿Qué comida cultivarías en Marte?",
  }),
  makeFact({
    slug: "fun-fact-vanilla-comes-from-orchids",
    postId: "fun-fact-vanilla-orchid",
    tags: ["fun-fact", "food", "plants", "science"],
    enTitle: "Did You Know? Vanilla Comes From an Orchid!",
    esTitle: "¿Sabías Que? ¡La Vainilla Viene de una Orquídea!",
    enSummary: "Vanilla flavor comes from pods produced by a special tropical orchid plant.",
    esSummary: "El sabor de vainilla viene de vainas producidas por una orquídea tropical especial.",
    enHeading: "A Flower Makes Vanilla! 🌸",
    esHeading: "¡Una Flor Produce Vainilla! 🌸",
    enFact: "Vanilla beans are seed pods from vanilla orchids. After careful curing, they become the sweet-smelling vanilla used in many treats.",
    esFact: "Las vainas de vainilla son frutos de orquídeas de vainilla. Después de curarlas con cuidado, se convierten en la vainilla aromática usada en muchos postres.",
    enPrompt: "Draw an orchid flower beside vanilla ice cream. Ask: What dessert smells the best to you?",
    esPrompt: "Dibuja una flor de orquídea junto a helado de vainilla. Pregunta: ¿Qué postre huele mejor para ti?",
  }),

  // ── Machines & Inventions (3) ──────────────────────
  makeFact({
    slug: "fun-fact-velcro-inspired-by-burrs",
    postId: "fun-fact-velcro-burrs",
    tags: ["fun-fact", "inventions", "machines", "science"],
    enTitle: "Did You Know? Velcro Was Inspired by Sticky Plant Burrs!",
    esTitle: "¿Sabías Que? ¡El Velcro se Inspiró en Plantas Pegajosas!",
    enSummary: "An inventor studied burrs stuck to clothing and copied their hook-and-loop idea.",
    esSummary: "Un inventor estudió plantas pegadas a la ropa y copió su idea de ganchos y lazos.",
    enHeading: "Nature Inspired an Invention! 🌱",
    esHeading: "¡La Naturaleza Inspiró un Invento! 🌱",
    enFact: "Swiss engineer George de Mestral noticed burrs sticking to his clothes and his dog's fur. Under a microscope, he saw tiny hooks and later developed Velcro.",
    esFact: "El ingeniero suizo George de Mestral notó que unas plantas se pegaban a su ropa y al pelo de su perro. Al verlas al microscopio encontró ganchitos y luego desarrolló el Velcro.",
    enPrompt: "Color a burr with tiny hooks beside a backpack strap. Ask: What invention could nature inspire next?",
    esPrompt: "Colorea una planta con ganchitos junto a una correa de mochila. Pregunta: ¿Qué invento podría inspirar la naturaleza después?",
  }),
  makeFact({
    slug: "fun-fact-traffic-light-before-cars",
    postId: "fun-fact-early-traffic-light",
    tags: ["fun-fact", "inventions", "machines", "history"],
    enTitle: "Did You Know? Traffic Lights Started Before Modern Cars!",
    esTitle: "¿Sabías Que? ¡Los Semáforos Empezaron Antes de los Autos Modernos!",
    enSummary: "An early traffic signal was used in London in 1868, when streets were full of horses and carriages.",
    esSummary: "Una señal de tráfico temprana se usó en Londres en 1868, cuando había caballos y carruajes.",
    enHeading: "Stop-and-Go Before Cars! 🚦",
    esHeading: "¡Alto y Siga Antes de los Autos! 🚦",
    enFact: "One early traffic signal appeared in London in 1868. It helped guide horse-drawn traffic before modern automobiles filled city streets.",
    esFact: "Una señal de tráfico temprana apareció en Londres en 1868. Ayudaba a guiar el tránsito de carruajes tirados por caballos antes de que los autos modernos llenaran las calles.",
    enPrompt: "Draw a street with horses, carriages, and a traffic light. Ask: What rules help people travel safely?",
    esPrompt: "Dibuja una calle con caballos, carruajes y un semáforo. Pregunta: ¿Qué reglas ayudan a viajar con seguridad?",
  }),
  makeFact({
    slug: "fun-fact-early-bicycles-no-pedals",
    postId: "fun-fact-first-bicycles-no-pedals",
    tags: ["fun-fact", "machines", "inventions", "history"],
    enTitle: "Did You Know? Some Early Bicycles Had No Pedals!",
    esTitle: "¿Sabías Que? ¡Algunas Bicicletas Antiguas No Tenían Pedales!",
    enSummary: "Early bicycle-like machines were pushed along by riders' feet instead of pedals.",
    esSummary: "Algunas máquinas parecidas a bicicletas se empujaban con los pies en vez de pedales.",
    enHeading: "A Bike You Had to Push! 🚲",
    esHeading: "¡Una Bici Que Había Que Empujar! 🚲",
    enFact: "One early bicycle-like invention, often called a draisine or running machine, had two wheels but no pedals. Riders pushed with their feet to move.",
    esFact: "Un invento antiguo parecido a una bicicleta, llamado draisiana o máquina de correr, tenía dos ruedas pero no pedales. Los pasajeros se impulsaban con los pies.",
    enPrompt: "Draw an old wooden bike next to a modern colorful bicycle. Ask: Which bike would be easier to ride?",
    esPrompt: "Dibuja una bici antigua de madera junto a una bicicleta moderna y colorida. Pregunta: ¿Cuál sería más fácil de usar?",
  }),

  // ── Colors & Art (3) ────────────────────────────────
  makeFact({
    slug: "fun-fact-purple-dye-rare-sea-snails",
    postId: "fun-fact-purple-dye-sea-snails",
    tags: ["fun-fact", "colors", "art", "history", "ocean"],
    enTitle: "Did You Know? Purple Dye Was Once Incredibly Rare!",
    esTitle: "¿Sabías Que? ¡El Tinte Morado Fue Muy Raro Durante Mucho Tiempo!",
    enSummary: "Ancient purple dye was made from sea snails, which made purple cloth very expensive.",
    esSummary: "El tinte morado antiguo se hacía con caracoles marinos, por eso la tela morada era muy cara.",
    enHeading: "A Royal Color Story! 💜",
    esHeading: "¡Una Historia de Color Real! 💜",
    enFact: "In ancient times, some purple dye came from sea snails. It took many snails and lots of work, so purple cloth became a sign of wealth and royalty.",
    esFact: "En la antigüedad, algunos tintes morados venían de caracoles marinos. Se necesitaban muchos caracoles y mucho trabajo, así que la tela morada se volvió símbolo de riqueza y realeza.",
    enPrompt: "Color a royal cape in deep purple with tiny sea snails nearby. Ask: What color would your royal cape be?",
    esPrompt: "Colorea una capa real de morado intenso con caracoles marinos cerca. Pregunta: ¿De qué color sería tu capa real?",
  }),
  makeFact({
    slug: "fun-fact-mauveine-first-synthetic-dye",
    postId: "fun-fact-mauveine-dye",
    tags: ["fun-fact", "colors", "art", "science", "history"],
    enTitle: "Did You Know? A Purple Dye Was Discovered by Accident!",
    esTitle: "¿Sabías Que? ¡Un Tinte Morado Fue Descubierto por Accidente!",
    enSummary: "Mauveine, an early synthetic dye, was discovered accidentally by William Henry Perkin in 1856.",
    esSummary: "La mauveína, un tinte sintético temprano, fue descubierta por accidente por William Henry Perkin en 1856.",
    enHeading: "A Colorful Accident! 🧪",
    esHeading: "¡Un Accidente Colorido! 🧪",
    enFact: "William Henry Perkin was trying to make medicine chemistry work in 1856 when he accidentally discovered a purple dye called mauveine.",
    esFact: "William Henry Perkin intentaba resolver un experimento de química médica en 1856 cuando descubrió por accidente un tinte morado llamado mauveína.",
    enPrompt: "Draw a safe pretend science table with purple color bubbles. Ask: What new color name would you invent?",
    esPrompt: "Dibuja una mesa de ciencia imaginaria con burbujas moradas. Pregunta: ¿Qué nombre inventarías para un color nuevo?",
  }),
  makeFact({
    slug: "fun-fact-some-animals-see-ultraviolet",
    postId: "fun-fact-ultraviolet-animal-vision",
    tags: ["fun-fact", "colors", "animals", "science"],
    enTitle: "Did You Know? Some Animals Can See Ultraviolet Light!",
    esTitle: "¿Sabías Que? ¡Algunos Animales Pueden Ver Luz Ultravioleta!",
    enSummary: "Bees, some birds, and other animals can see colors humans cannot see.",
    esSummary: "Abejas, algunas aves y otros animales pueden ver colores que los humanos no vemos.",
    enHeading: "Hidden Colors in Nature! 🐝",
    esHeading: "¡Colores Escondidos en la Naturaleza! 🐝",
    enFact: "Humans cannot see ultraviolet light, but some animals can. Bees use ultraviolet patterns on flowers to help find nectar.",
    esFact: "Los humanos no podemos ver la luz ultravioleta, pero algunos animales sí. Las abejas usan patrones ultravioletas en las flores para encontrar néctar.",
    enPrompt: "Color a flower twice: once for people and once for bees. Ask: What secret pattern would your flower show?",
    esPrompt: "Colorea una flor dos veces: una para personas y otra para abejas. Pregunta: ¿Qué patrón secreto mostraría tu flor?",
  }),

  // ── History & Words (3) ─────────────────────────────
  makeFact({
    slug: "fun-fact-alphabet-from-alpha-beta",
    postId: "fun-fact-alphabet-alpha-beta",
    tags: ["fun-fact", "language", "history"],
    enTitle: "Did You Know? Alphabet Comes From Alpha and Beta!",
    esTitle: "¿Sabías Que? ¡La Palabra Alfabeto Viene de Alfa y Beta!",
    enSummary: "The word alphabet comes from the first two letters of the Greek alphabet: alpha and beta.",
    esSummary: "La palabra alfabeto viene de las dos primeras letras del alfabeto griego: alfa y beta.",
    enHeading: "A Word Built From Letters! 🔤",
    esHeading: "¡Una Palabra Construida con Letras! 🔤",
    enFact: "The word alphabet comes from alpha and beta, the first two letters of the Greek alphabet. Languages often carry history inside everyday words.",
    esFact: "La palabra alfabeto viene de alfa y beta, las dos primeras letras del alfabeto griego. Los idiomas guardan historia dentro de palabras cotidianas.",
    enPrompt: "Draw alpha, beta, and your favorite letter as characters. Ask: Which letter would be the leader?",
    esPrompt: "Dibuja alfa, beta y tu letra favorita como personajes. Pregunta: ¿Qué letra sería la líder?",
  }),
  makeFact({
    slug: "fun-fact-sandwich-named-after-earl",
    postId: "fun-fact-sandwich-name",
    tags: ["fun-fact", "history", "language", "food"],
    enTitle: "Did You Know? Sandwich Is Named After a Person!",
    esTitle: "¿Sabías Que? ¡El Sándwich Lleva el Nombre de una Persona!",
    enSummary: "The word sandwich is linked to the Earl of Sandwich, an English nobleman from the 1700s.",
    esSummary: "La palabra sándwich se relaciona con el Conde de Sandwich, un noble inglés del siglo XVIII.",
    enHeading: "A Snack With a Name Story! 🥪",
    esHeading: "¡Un Bocadillo con Historia de Nombre! 🥪",
    enFact: "The sandwich is named after John Montagu, the 4th Earl of Sandwich. Stories say he liked eating meat between bread so he could keep playing cards.",
    esFact: "El sándwich lleva el nombre de John Montagu, cuarto Conde de Sandwich. Las historias dicen que le gustaba comer carne entre panes para seguir jugando cartas.",
    enPrompt: "Design a silly sandwich with colorful layers. Ask: What would your famous sandwich be called?",
    esPrompt: "Diseña un sándwich divertido con capas de colores. Pregunta: ¿Cómo se llamaría tu sándwich famoso?",
  }),
  makeFact({
    slug: "fun-fact-robot-word-czech-origin",
    postId: "fun-fact-robot-word-origin",
    tags: ["fun-fact", "language", "history", "machines"],
    enTitle: "Did You Know? The Word Robot Comes From Czech!",
    esTitle: "¿Sabías Que? ¡La Palabra Robot Viene del Checo!",
    enSummary: "The word robot became popular from a Czech play written over 100 years ago.",
    esSummary: "La palabra robot se hizo popular por una obra checa escrita hace más de 100 años.",
    enHeading: "A Word From a Play! 🤖",
    esHeading: "¡Una Palabra Nacida en una Obra! 🤖",
    enFact: "The word robot became famous from the Czech play R.U.R., published in 1920. It helped shape the way people talk about human-made helpers.",
    esFact: "La palabra robot se hizo famosa por la obra checa R.U.R., publicada en 1920. Ayudó a formar la manera en que hablamos de ayudantes creados por humanos.",
    enPrompt: "Draw a friendly robot holding a dictionary. Ask: What helpful job would your robot do?",
    esPrompt: "Dibuja un robot amable sosteniendo un diccionario. Pregunta: ¿Qué trabajo útil haría tu robot?",
  }),

  // ── World Records (3) ───────────────────────────────
  makeFact({
    slug: "fun-fact-mount-everest-highest-above-sea-level",
    postId: "fun-fact-everest-height-record",
    tags: ["fun-fact", "records", "world-records", "earth"],
    enTitle: "Did You Know? Mount Everest Is the Highest Mountain Above Sea Level!",
    esTitle: "¿Sabías Que? ¡El Monte Everest Es la Montaña Más Alta Sobre el Nivel del Mar!",
    enSummary: "Mount Everest rises about 29,032 feet above sea level, making it Earth's highest mountain by that measure.",
    esSummary: "El Monte Everest mide unos 29,032 pies sobre el nivel del mar, la mayor altura por esa medida.",
    enHeading: "A Mountain That Touches the Sky! 🏔️",
    esHeading: "¡Una Montaña que Toca el Cielo! 🏔️",
    enFact: "Mount Everest is about 29,032 feet (8,849 m) above sea level. Climbers train carefully because the top is extremely cold and high.",
    esFact: "El Monte Everest mide cerca de 29,032 pies (8,849 m) sobre el nivel del mar. Los alpinistas se preparan mucho porque la cima es extremadamente fría y alta.",
    enPrompt: "Draw Everest with colorful flags and clouds below the peak. Ask: What would you pack for a mountain adventure?",
    esPrompt: "Dibuja el Everest con banderas de colores y nubes bajo la cima. Pregunta: ¿Qué empacarías para una aventura en la montaña?",
  }),
  makeFact({
    slug: "fun-fact-cheetah-fastest-land-animal",
    postId: "fun-fact-cheetah-speed-record",
    tags: ["fun-fact", "records", "world-records", "animals"],
    enTitle: "Did You Know? The Cheetah Is the Fastest Land Animal!",
    esTitle: "¿Sabías Que? ¡El Guepardo Es el Animal Terrestre Más Rápido!",
    enSummary: "Cheetahs can sprint at incredible speeds for short bursts while chasing prey.",
    esSummary: "Los guepardos pueden correr a velocidades increíbles durante carreras cortas al cazar.",
    enHeading: "A Spotted Speed Champion! 🐆",
    esHeading: "¡Un Campeón de Velocidad con Manchas! 🐆",
    enFact: "Cheetahs are built for short, super-fast sprints. They can reach around 60 to 70 miles per hour for brief moments.",
    esFact: "Los guepardos están hechos para carreras cortas y rapidísimas. Pueden alcanzar cerca de 60 a 70 millas por hora por momentos breves.",
    enPrompt: "Color a cheetah racing with motion lines behind it. Ask: What animal would join your pretend race?",
    esPrompt: "Colorea un guepardo corriendo con líneas de movimiento detrás. Pregunta: ¿Qué animal se uniría a tu carrera imaginaria?",
  }),
  makeFact({
    slug: "fun-fact-angel-falls-tallest-waterfall",
    postId: "fun-fact-angel-falls-record",
    tags: ["fun-fact", "records", "world-records", "earth"],
    enTitle: "Did You Know? Angel Falls Is the Tallest Uninterrupted Waterfall!",
    esTitle: "¿Sabías Que? ¡El Salto Ángel Es la Cascada Ininterrumpida Más Alta!",
    enSummary: "Angel Falls in Venezuela drops from a tabletop mountain in one of the world's tallest waterfall plunges.",
    esSummary: "El Salto Ángel en Venezuela cae desde una montaña plana en una de las caídas de agua más altas del mundo.",
    enHeading: "A Waterfall Record! 💧",
    esHeading: "¡Un Récord de Cascada! 💧",
    enFact: "Angel Falls is known as the world's tallest uninterrupted waterfall, dropping about 3,212 feet (979 m) from a high cliff in Venezuela.",
    esFact: "El Salto Ángel es conocido como la cascada ininterrumpida más alta del mundo, con una caída de unos 3,212 pies (979 m) desde un acantilado en Venezuela.",
    enPrompt: "Draw a tall waterfall falling from clouds into a jungle river. Ask: What animals might hear the roar of the water?",
    esPrompt: "Dibuja una cascada alta cayendo desde las nubes hacia un río selvático. Pregunta: ¿Qué animales podrían escuchar el rugido del agua?",
  }),
];

export default {
  batch: 2,
  name: "Batch 02 — SEO-balanced curiosity expansion",
  description:
    "Adds 30 bilingual fun facts across all 10 categories, with extra evergreen science, records, and kid-friendly discovery prompts.",
  facts,
};